##Importing the Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

##Importing the Dataset

In [2]:
df = pd.read_csv('/content/final_data_HF.csv')
df.drop('ID', axis=1 , inplace=True)

In [3]:
df.head()

Gender  Age Alchohol Smoking Non-Veg Exercise         Medication   BMI  \
0    Male   37       No      No      No       No                 No  24.1   
1    Male   47       No      No      No      Yes  Yes(Anxiety/B.P.)  22.8   
2  Female   47       No      No      No       No       Yes(Thyroid)  28.0   
3  Female   35       No      No      No       No                 No  27.4   
4  Female   33       No      No      No       No                 No  22.6   

   HF_best  
0        2  
1        2  
2        2  
3        2  
4        3

In [4]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(sampling_strategy="not majority")
X_res, y_res = ros.fit_resample(X, y)

In [5]:
y_res

0      2
1      2
2      2
3      2
4      3
      ..
97     5
98     5
99     5
100    5
101    5
Name: HF_best, Length: 102, dtype: int64

In [6]:
y_res.value_counts()

2    17
3    17
5    17
4    17
6    17
1    17
Name: HF_best, dtype: int64

In [7]:
X = X_res.values
y = y_res.values

In [8]:
X

array([['Male', 37, 'No', 'No', 'No', 'No', 'No', 24.1],
       ['Male', 47, 'No', 'No', 'No', 'Yes', 'Yes(Anxiety/B.P.)', 22.8],
       ['Female', 47, 'No', 'No', 'No', 'No', 'Yes(Thyroid)', 28.0],
       ['Female', 35, 'No', 'No', 'No', 'No', 'No', 27.4],
       ['Female', 33, 'No', 'No', 'No', 'No', 'No', 22.6],
       ['Female', 45, 'No', 'No', 'No', 'No', 'Yes(B.P.)', 24.5],
       ['Female', 41, 'No', 'No', 'No', 'No', 'No', 24.5],
       ['Female', 36, 'No', 'No', 'No', 'No', 'No', 23.2],
       ['Female', 35, 'No', 'No', 'Yes', 'No', 'Yes(Thyroid)', 25.0],
       ['Male', 38, 'Yes', 'No', 'Yes', 'No', 'No', 25.8],
       ['Male', 43, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 30.1],
       ['Male', 39, 'No', 'No', 'No', 'Yes', 'Yes', 25.4],
       ['Male', 34, 'Yes', 'No', 'Yes', 'No', 'No', 23.9],
       ['Female', 34, 'No', 'No', 'No', 'No', 'No', 22.1],
       ['Female', 29, 'No', 'No', 'Yes', 'No', 'No', 25.7],
       ['Male', 28, 'No', 'No', 'Yes', 'Yes', 'No', 24.0],
       ['Male

##LabelEncoding

In [9]:
for i in range(X.shape[0]):
  for j in range(0, 6):
    if X[i, j] == 'No' or X[i,j] == "Male" or X[i, j] == 'No ':
      X[i, j] = 0
    elif X[i, j] == 'Yes' or X[i,j] == "Female":
      X[i, j] = 1

for i in range(X.shape[0]):
  for j in range(6,7):
    if X[i,j] == 'No':
      X[i,j] = 0
    else:
      X[i,j] = 1
X

array([[0, 37, 0, 0, 0, 0, 0, 24.1],
       [0, 47, 0, 0, 0, 1, 1, 22.8],
       [1, 47, 0, 0, 0, 0, 1, 28.0],
       [1, 35, 0, 0, 0, 0, 0, 27.4],
       [1, 33, 0, 0, 0, 0, 0, 22.6],
       [1, 45, 0, 0, 0, 0, 1, 24.5],
       [1, 41, 0, 0, 0, 0, 0, 24.5],
       [1, 36, 0, 0, 0, 0, 0, 23.2],
       [1, 35, 0, 0, 1, 0, 1, 25.0],
       [0, 38, 1, 0, 1, 0, 0, 25.8],
       [0, 43, 1, 1, 1, 0, 1, 30.1],
       [0, 39, 0, 0, 0, 1, 1, 25.4],
       [0, 34, 1, 0, 1, 0, 0, 23.9],
       [1, 34, 0, 0, 0, 0, 0, 22.1],
       [1, 29, 0, 0, 1, 0, 0, 25.7],
       [0, 28, 0, 0, 1, 1, 0, 24.0],
       [0, 28, 0, 0, 1, 0, 0, 24.3],
       [0, 29, 0, 0, 1, 1, 0, 25.0],
       [0, 30, 0, 0, 1, 0, 0, 24.6],
       [0, 34, 0, 0, 1, 1, 0, 28.4],
       [0, 35, 0, 0, 0, 1, 0, 24.3],
       [0, 39, 0, 0, 1, 0, 0, 24.3],
       [0, 30, 0, 0, 1, 1, 0, 26.8],
       [0, 45, 0, 0, 1, 0, 1, 21.2],
       [0, 36, 0, 0, 0, 1, 1, 23.8],
       [0, 28, 0, 0, 1, 0, 0, 22.0],
       [0, 41, 0, 0, 0, 1, 0, 20.9],
 

##Splitting the Dataset

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [11]:
X_train.shape

(81, 8)

##Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.fit_transform(X_test)

##Normalisation

In [13]:
from sklearn.preprocessing import Normalizer
nl_1 = Normalizer()

X_train_normal = nl_1.fit_transform(X_train)
X_test_normal = nl_1.transform(X_test)

#MODELS

In [14]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier, BaggingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.neural_network import MLPClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

In [15]:
# Function to print evaluation metrics
def print_metrics(y_true, y_pred):
    accuracy = accuracy_score(y_true, y_pred)
    precision_micro = precision_score(y_true, y_pred, average='micro')
    recall_micro = recall_score(y_true, y_pred, average='micro')
    f1_micro = f1_score(y_true, y_pred, average='micro')

    precision_macro = precision_score(y_true, y_pred, average='macro')
    recall_macro = recall_score(y_true, y_pred, average='macro')
    f1_macro = f1_score(y_true, y_pred, average='macro')

    precision_weighted = precision_score(y_true, y_pred, average='weighted')
    recall_weighted = recall_score(y_true, y_pred, average='weighted')
    f1_weighted = f1_score(y_true, y_pred, average='weighted')

    print(f"Accuracy: {accuracy:.10f}")
    print("\nMicro-average:")
    print(f"Precision: {precision_micro:.10f}")
    print(f"Recall: {recall_micro:.10f}")
    print(f"F1 Score: {f1_micro:.10f}")

    print("\nMacro-average:")
    print(f"Precision: {precision_macro:.10f}")
    print(f"Recall: {recall_macro:.10f}")
    print(f"F1 Score: {f1_macro:.10f}")

    print("\nWeighted-average:")
    print(f"Precision: {precision_weighted:.10f}")
    print(f"Recall: {recall_weighted:.10f}")
    print(f"F1 Score: {f1_weighted:.10f}")

In [16]:
import warnings
warnings.filterwarnings("ignore")

###Logistic Regression

In [19]:
lr = LogisticRegression()
lr_params = {
    'penalty': ['l1', 'l2'],
    'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000],
    'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],
    'max_iter': [50, 100, 200, 500, 1000],
    'class_weight': [None, 'balanced'],
    'random_state': [42]
}
grid_lr = GridSearchCV(lr, lr_params, cv=5)
grid_lr.fit(X_train_scaled, y_train)
y_pred_lr = grid_lr.predict(X_test_scaled)

# Print details of the Logistic Regression model
print("Logistic Regression:")
print("Best Parameters:", grid_lr.best_params_)
print("Best Score:", grid_lr.best_score_* 100 )
print_metrics(y_test, y_pred_lr)
print("\n")

Logistic Regression:
Best Parameters: {'C': 10, 'class_weight': None, 'max_iter': 50, 'penalty': 'l1', 'random_state': 42, 'solver': 'liblinear'}
Best Score: 37.05882352941177
Accuracy: 0.3333333333

Micro-average:
Precision: 0.3333333333
Recall: 0.3333333333
F1 Score: 0.3333333333

Macro-average:
Precision: 0.2722222222
Recall: 0.3166666667
F1 Score: 0.2888888889

Weighted-average:
Precision: 0.3031746032
Recall: 0.3333333333
F1 Score: 0.3132275132




##KNeighbors

In [ ]:
knn = KNeighborsClassifier()
knn_params = {
    'n_neighbors': [3, 5, 7, 9, 11, 15, 20],
    'weights': ['uniform', 'distance'],
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'leaf_size': [30, 40, 50, 60],
    'p': [1, 2]
}
grid_knn = GridSearchCV(knn, knn_params, cv=5)
grid_knn.fit(X_train_scaled, y_train)
y_pred_knn = grid_knn.predict(X_test_scaled)

# Print details of the k-Nearest Neighbors model
print("k-Nearest Neighbors:")
print("Best Parameters:", grid_knn.best_params_)
print("Best Score:", grid_knn.best_score_)
print_metrics(y_test, y_pred_knn)
print("\n")

k-Nearest Neighbors:
Best Parameters: {'algorithm': 'auto', 'leaf_size': 30, 'n_neighbors': 3, 'p': 1, 'weights': 'distance'}
Best Score: 0.7161764705882353
Accuracy: 0.4761904762

Micro-average:
Precision: 0.4761904762
Recall: 0.4761904762
F1 Score: 0.4761904762

Macro-average:
Precision: 0.4796296296
Recall: 0.4250000000
F1 Score: 0.3942307692

Weighted-average:
Precision: 0.5449735450
Recall: 0.4761904762
F1 Score: 0.4434065934




##SVC

In [17]:
svm = SVC()
svm_params = {
    'C': [0.1, 1, 10, 100, 1000],
    'kernel': ['linear', 'rbf', 'poly', 'sigmoid'],
    'gamma': ['scale', 'auto', 0.1, 1, 10, 100],
    'degree': [2, 3, 4],
    'coef0': [0.0, 0.5, 1.0]
}

grid_svm = GridSearchCV(svm, svm_params, cv=5)
grid_svm.fit(X_train_scaled, y_train)
y_pred_svm = grid_svm.predict(X_test_scaled)

# Print details of the Support Vector Machines model
print("Support Vector Machines:")
print("Best Parameters:", grid_svm.best_params_)
print("Best Score:", grid_svm.best_score_)
print_metrics(y_test, y_pred_svm)
print("\n")


Support Vector Machines:
Best Parameters: {'C': 1, 'coef0': 0.0, 'degree': 2, 'gamma': 100, 'kernel': 'rbf'}
Best Score: 0.7522058823529412
Accuracy: 0.2380952381

Micro-average:
Precision: 0.2380952381
Recall: 0.2380952381
F1 Score: 0.2380952381

Macro-average:
Precision: 0.0396825397
Recall: 0.1666666667
F1 Score: 0.0641025641

Weighted-average:
Precision: 0.0566893424
Recall: 0.2380952381
F1 Score: 0.0915750916




##Decision Trees

In [18]:
dt = DecisionTreeClassifier()
dt_params = {
    'criterion': ['gini', 'entropy'],
    'splitter': ['best', 'random'],
    'max_depth': [None, 5, 10, 20, 30, 50, 100],
    'min_samples_split': [2, 5, 10, 20, 30, 50],
    'min_samples_leaf': [1, 2, 4, 8, 10, 20]
}

grid_dt = GridSearchCV(dt, dt_params, cv=5)
grid_dt.fit(X_train, y_train)
y_pred_dt = grid_dt.predict(X_test)

# Print details of the Decision Trees model
print("Decision Trees:")
print("Best Parameters:", grid_dt.best_params_)
print("Best Score:", grid_dt.best_score_)
print_metrics(y_test, y_pred_dt)
print("\n")


Decision Trees:
Best Parameters: {'criterion': 'gini', 'max_depth': 50, 'min_samples_leaf': 1, 'min_samples_split': 2, 'splitter': 'random'}
Best Score: 0.6911764705882353
Accuracy: 0.7142857143

Micro-average:
Precision: 0.7142857143
Recall: 0.7142857143
F1 Score: 0.7142857143

Macro-average:
Precision: 0.7444444444
Recall: 0.8000000000
F1 Score: 0.6842592593

Weighted-average:
Precision: 0.8269841270
Recall: 0.7142857143
F1 Score: 0.6748677249




##Random Forest

In [21]:
rf = RandomForestClassifier()
rf_params = {
    'n_estimators': [50, 100, 200, 400, 800],
    'criterion': ['gini'],
    'max_depth': [None, 5, 10, 20,50],
    'min_samples_leaf': [1, 2, 4, 8]
}
grid_rf = GridSearchCV(rf, rf_params, cv=5)
grid_rf.fit(X_train, y_train)
y_pred_rf = grid_rf.predict(X_test)

# Print details of the Random Forest model
print("Random Forest:")
print("Best Parameters:", grid_rf.best_params_)
print("Best Score:", grid_rf.best_score_)
print_metrics(y_test, y_pred_rf)
print("\n")

Random Forest:
Best Parameters: {'criterion': 'gini', 'max_depth': 50, 'min_samples_leaf': 1, 'n_estimators': 100}
Best Score: 0.7036764705882353
Accuracy: 0.6666666667

Micro-average:
Precision: 0.6666666667
Recall: 0.6666666667
F1 Score: 0.6666666667

Macro-average:
Precision: 0.6285714286
Recall: 0.7666666667
F1 Score: 0.6562650313

Weighted-average:
Precision: 0.5850340136
Recall: 0.6666666667
F1 Score: 0.5884525527




##Gradient Boosting

In [23]:
# gb = GradientBoostingClassifier()
# gb_params = {
#     'n_estimators': [50, 100, 200, 400, 800],
#     'learning_rate': [0.001, 0.01, 0.1, 0.2, 0.5],
#     'max_depth': [3, 5, 7, 9],
#     'min_samples_split': [2, 5, 10, 20, 30],
#     'min_samples_leaf': [1, 2, 4, 8],
# }
# grid_gb = GridSearchCV(gb, gb_params, cv=5)
# grid_gb.fit(X_train, y_train)
# y_pred_gb = grid_gb.predict(X_test)

# # Print details of the Gradient Boosting model
# print("Gradient Boosting:")
# print("Best Parameters:", grid_gb.best_params_)
# print("Best Score:", grid_gb.best_score_)
# print_metrics(y_test, y_pred_gb)
# print("\n")

##AdaBoost

In [24]:
ada = AdaBoostClassifier()
ada_params = {
    'n_estimators': [50, 100, 200, 400, 800],
    'learning_rate': [0.001, 0.01, 0.1, 0.2, 0.5],
}
grid_ada = GridSearchCV(ada, ada_params, cv=5)
grid_ada.fit(X_train, y_train)
y_pred_ada = grid_ada.predict(X_test)

# Print details of the AdaBoost model
print("AdaBoost:")
print("Best Parameters:", grid_ada.best_params_)
print("Best Score:", grid_ada.best_score_)
print_metrics(y_test, y_pred_ada)
print("\n")


AdaBoost:
Best Parameters: {'learning_rate': 0.5, 'n_estimators': 50}
Best Score: 0.41911764705882354
Accuracy: 0.3809523810

Micro-average:
Precision: 0.3809523810
Recall: 0.3809523810
F1 Score: 0.3809523810

Macro-average:
Precision: 0.3809523810
Recall: 0.3583333333
F1 Score: 0.3608706109

Weighted-average:
Precision: 0.4115646259
Recall: 0.3809523810
F1 Score: 0.3859685288




##BaggingClassifier

In [25]:
bag = BaggingClassifier()
bag_params = {
    'n_estimators': [50, 100, 200, 400, 800],
    'max_samples': [0.1, 0.5, 1.0],
    'max_features': [0.1, 0.5, 1.0],
}
grid_bag = GridSearchCV(bag, bag_params, cv=5)
grid_bag.fit(X_train, y_train)
y_pred_bag = grid_bag.predict(X_test)

# Print details of the Bagging model
print("Bagging:")
print("Best Parameters:", grid_bag.best_params_)
print("Best Score:", grid_bag.best_score_)
print_metrics(y_test, y_pred_bag)
print("\n")

Bagging:
Best Parameters: {'max_features': 0.5, 'max_samples': 0.5, 'n_estimators': 200}
Best Score: 0.6911764705882353
Accuracy: 0.6190476190

Micro-average:
Precision: 0.6190476190
Recall: 0.6190476190
F1 Score: 0.6190476190

Macro-average:
Precision: 0.5416666667
Recall: 0.7250000000
F1 Score: 0.5777777778

Weighted-average:
Precision: 0.5555555556
Recall: 0.6190476190
F1 Score: 0.5484126984




##Gaussian Naive Bayes

In [26]:
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred_gnb = gnb.predict(X_test)

# Print details of the Gaussian Naive Bayes model
print("Gaussian Naive Bayes:")
print_metrics(y_test, y_pred_gnb)
print("\n")

Gaussian Naive Bayes:
Accuracy: 0.2857142857

Micro-average:
Precision: 0.2857142857
Recall: 0.2857142857
F1 Score: 0.2857142857

Macro-average:
Precision: 0.1500000000
Recall: 0.2333333333
F1 Score: 0.1693121693

Weighted-average:
Precision: 0.1952380952
Recall: 0.2857142857
F1 Score: 0.2146636432




##LDA

In [27]:
lda = LinearDiscriminantAnalysis()
lda.fit(X_train, y_train)
y_pred_lda = lda.predict(X_test)

# Print details of the Linear Discriminant Analysis model
print("Linear Discriminant Analysis:")
print_metrics(y_test, y_pred_lda)
print("\n")

Linear Discriminant Analysis:
Accuracy: 0.3333333333

Micro-average:
Precision: 0.3333333333
Recall: 0.3333333333
F1 Score: 0.3333333333

Macro-average:
Precision: 0.2492063492
Recall: 0.2750000000
F1 Score: 0.2528138528

Weighted-average:
Precision: 0.3038548753
Recall: 0.3333333333
F1 Score: 0.3079777365




##Quadratic Discriminant Analysis

In [28]:
qda = QuadraticDiscriminantAnalysis()
qda.fit(X_train, y_train)
y_pred_qda = qda.predict(X_test)

# Print details of the Quadratic Discriminant Analysis model
print("Quadratic Discriminant Analysis:")
print_metrics(y_test, y_pred_qda)
print("\n")


Quadratic Discriminant Analysis:
Accuracy: 0.0476190476

Micro-average:
Precision: 0.0476190476
Recall: 0.0476190476
F1 Score: 0.0476190476

Macro-average:
Precision: 0.0079365079
Recall: 0.1666666667
F1 Score: 0.0151515152

Weighted-average:
Precision: 0.0022675737
Recall: 0.0476190476
F1 Score: 0.0043290043




##Multi-layer Perceptron

In [29]:
mlp = MLPClassifier()
mlp_params = {
    'hidden_layer_sizes': [(100,), (50, 50), (100, 50), (100, 100)],
    'activation': ['relu', 'tanh', 'logistic'],
    'solver': ['adam', 'sgd'],
    'learning_rate': ['constant', 'invscaling', 'adaptive'],
    'max_iter': [100, 200, 400, 800]
}
grid_mlp = GridSearchCV(mlp, mlp_params, cv=5)
grid_mlp.fit(X_train_scaled, y_train)
y_pred_mlp = grid_mlp.predict(X_test_scaled)

# Print details of the Multi-layer Perceptron model
print("Multi-layer Perceptron (Neural Network):")
print("Best Parameters:", grid_mlp.best_params_)
print("Best Score:", grid_mlp.best_score_)
print_metrics(y_test, y_pred_mlp)
print("\n")

Multi-layer Perceptron (Neural Network):
Best Parameters: {'activation': 'logistic', 'hidden_layer_sizes': (100, 100), 'learning_rate': 'invscaling', 'max_iter': 800, 'solver': 'adam'}
Best Score: 0.7161764705882353
Accuracy: 0.6190476190

Micro-average:
Precision: 0.6190476190
Recall: 0.6190476190
F1 Score: 0.6190476190

Macro-average:
Precision: 0.6055555556
Recall: 0.7166666667
F1 Score: 0.6044973545

Weighted-average:
Precision: 0.6603174603
Recall: 0.6190476190
F1 Score: 0.6035525321




##Gaussian Process Classifier

In [30]:
gpc = GaussianProcessClassifier()
gpc_params = {
    'kernel': [1.0 * RBF(), 2.0 * RBF()],
}
grid_gpc = GridSearchCV(gpc, gpc_params, cv=5)
grid_gpc.fit(X_train_scaled, y_train)
y_pred_gpc = grid_gpc.predict(X_test_scaled)

# Print details of the Gaussian Process Classifier model
print("Gaussian Process Classifier:")
print("Best Parameters:", grid_gpc.best_params_)
print("Best Score:", grid_gpc.best_score_)
print_metrics(y_test, y_pred_gpc)
print("\n")


Gaussian Process Classifier:
Best Parameters: {'kernel': 1**2 * RBF(length_scale=1)}
Best Score: 0.39191176470588235
Accuracy: 0.1428571429

Micro-average:
Precision: 0.1428571429
Recall: 0.1428571429
F1 Score: 0.1428571429

Macro-average:
Precision: 0.0794871795
Recall: 0.2333333333
F1 Score: 0.0904761905

Weighted-average:
Precision: 0.0989010989
Recall: 0.1428571429
F1 Score: 0.1020408163




##Dummy Classifier

In [31]:
dummy = DummyClassifier(strategy="most_frequent")
dummy.fit(X_train, y_train)
y_pred_dummy = dummy.predict(X_test)

# Print details of the Dummy Classifier
print("Dummy Classifier:")
print_metrics(y_test, y_pred_dummy)
print("\n")

Dummy Classifier:
Accuracy: 0.0476190476

Micro-average:
Precision: 0.0476190476
Recall: 0.0476190476
F1 Score: 0.0476190476

Macro-average:
Precision: 0.0079365079
Recall: 0.1666666667
F1 Score: 0.0151515152

Weighted-average:
Precision: 0.0022675737
Recall: 0.0476190476
F1 Score: 0.0043290043




##Bagging Decision Trees

In [32]:
bag_dt = BaggingClassifier(base_estimator=DecisionTreeClassifier())
bag_dt_params = {
    'n_estimators': [50, 100, 200, 400, 800],
    'max_samples': [0.1, 0.5, 1.0],
    'max_features': [0.1, 0.5, 1.0],
}
grid_bag_dt = GridSearchCV(bag_dt, bag_dt_params, cv=5)
grid_bag_dt.fit(X_train, y_train)
y_pred_bag_dt = grid_bag_dt.predict(X_test)

# Print details of the Bagging Decision Trees model
print("Bagging Decision Trees:")
print("Best Parameters:", grid_bag_dt.best_params_)
print("Best Score:", grid_bag_dt.best_score_)
print_metrics(y_test, y_pred_bag_dt)
print("\n")

Bagging Decision Trees:
Best Parameters: {'max_features': 0.5, 'max_samples': 1.0, 'n_estimators': 400}
Best Score: 0.7036764705882353
Accuracy: 0.6666666667

Micro-average:
Precision: 0.6666666667
Recall: 0.6666666667
F1 Score: 0.6666666667

Macro-average:
Precision: 0.5619047619
Recall: 0.7666666667
F1 Score: 0.6110269360

Weighted-average:
Precision: 0.5786848073
Recall: 0.6666666667
F1 Score: 0.5864117364




##AdaBoost with Decision Trees

In [33]:
ada_dt = AdaBoostClassifier(base_estimator=DecisionTreeClassifier())
ada_dt_params = {
    'n_estimators': [50, 100, 200, 400, 800],
    'learning_rate': [0.001, 0.01, 0.1, 0.2, 0.5],
}
grid_ada_dt = GridSearchCV(ada_dt, ada_dt_params, cv=5)
grid_ada_dt.fit(X_train, y_train)
y_pred_ada_dt = grid_ada_dt.predict(X_test)

# Print details of the AdaBoost with Decision Trees model
print("AdaBoost with Decision Trees:")
print("Best Parameters:", grid_ada_dt.best_params_)
print("Best Score:", grid_ada_dt.best_score_)
print_metrics(y_test, y_pred_ada_dt)
print("\n")

AdaBoost with Decision Trees:
Best Parameters: {'learning_rate': 0.01, 'n_estimators': 50}
Best Score: 0.6786764705882353
Accuracy: 0.7142857143

Micro-average:
Precision: 0.7142857143
Recall: 0.7142857143
F1 Score: 0.7142857143

Macro-average:
Precision: 0.8119047619
Recall: 0.8000000000
F1 Score: 0.7276936027

Weighted-average:
Precision: 0.8326530612
Recall: 0.7142857143
F1 Score: 0.6768879269




##XGBoost

In [ ]:
import xgboost as xgb
y_train_reduced = y_train - 1
y_test_reduced = y_test - 1

# Rest of your code remains the same
xgb_model = xgb.XGBClassifier()
xgb_params = {
    'max_depth': [3, 5, 7, 9],
    'learning_rate': [0.001, 0.01, 0.1, 0.2, 0.5],
    'n_estimators': [50, 100, 200, 400, 800]
}
grid_xgb = GridSearchCV(xgb_model, xgb_params, cv=5)
grid_xgb.fit(X_train, y_train_reduced)
y_pred_xgb = grid_xgb.predict(X_test)

# Print details of the XGBoost model
print("XGBoost:")
print("Best Parameters:", grid_xgb.best_params_)
print("Best Score:", grid_xgb.best_score_)
print_metrics(y_test_reduced, y_pred_xgb)
print("\n")


##Catboost

In [26]:
!pip install catboost

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.6/98.6 MB 9.3 MB/s eta 0:00:00


In [27]:
from catboost import CatBoostClassifier
cboost = CatBoostClassifier()

parameters = [{'n_estimators': [1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000]}]
grid_search = GridSearchCV(estimator = cboost,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

Learning rate set to 0.069607
0:	learn: 1.7655776	total: 46.8ms	remaining: 46.8s
1:	learn: 1.7331391	total: 48ms	remaining: 24s
2:	learn: 1.7033259	total: 49.3ms	remaining: 16.4s
3:	learn: 1.6749982	total: 50.4ms	remaining: 12.5s
4:	learn: 1.6431073	total: 51.5ms	remaining: 10.2s
5:	learn: 1.6300674	total: 52.1ms	remaining: 8.64s
6:	learn: 1.6050443	total: 53.2ms	remaining: 7.54s
7:	learn: 1.5812724	total: 54.2ms	remaining: 6.72s
8:	learn: 1.5523974	total: 55.3ms	remaining: 6.08s
9:	learn: 1.5282384	total: 56.4ms	remaining: 5.58s
10:	learn: 1.5004696	total: 57.4ms	remaining: 5.16s
11:	learn: 1.4774192	total: 58.5ms	remaining: 4.81s
12:	learn: 1.4504431	total: 59.6ms	remaining: 4.52s
13:	learn: 1.4303719	total: 60.6ms	remaining: 4.27s
14:	learn: 1.4116601	total: 61.7ms	remaining: 4.05s
15:	learn: 1.3900776	total: 62.7ms	remaining: 3.85s
16:	learn: 1.3704523	total: 63.7ms	remaining: 3.68s
17:	learn: 1.3559180	total: 64.8ms	remaining: 3.54s
18:	learn: 1.3359475	total: 65.9ms	remaining: 3.

##ADABoost

In [17]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import AdaBoostClassifier
ada = AdaBoostClassifier()

parameters = [{'estimator': [RandomForestClassifier(), GradientBoostingClassifier()], 'n_estimators': [1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000]}]
grid_search = GridSearchCV(estimator = ada,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

Best Accuracy: 70.56 %
Best Parameters: {'estimator': RandomForestClassifier(), 'n_estimators': 3000}


In [18]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
ada = AdaBoostClassifier()

parameters = [{'estimator': [AdaBoostClassifier(estimator=RandomForestClassifier(n_estimators=5000), n_estimators=10000, learning_rate=0.01)], 'n_estimators': [10, 50, 100, 500, 1000, 2000, 5000], 'learning_rate' : [0.1, 0.01, 0.001]}]
grid_search = GridSearchCV(estimator = ada,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

Best Accuracy: 69.31 %
Best Parameters: {'estimator': AdaBoostClassifier(estimator=RandomForestClassifier(n_estimators=5000),
                   learning_rate=0.01, n_estimators=10000), 'learning_rate': 0.1, 'n_estimators': 100}


In [19]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score


ada2 = AdaBoostClassifier(estimator=GradientBoostingClassifier(n_estimators=5000), n_estimators=10000, learning_rate=0.01, random_state=0)
accuracies = cross_val_score(estimator = ada2, X = X_train, y = y_train, cv = 6)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 74.08 %
Standard Deviation: 9.26 %


In [20]:
# accuracies

In [21]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier

ada_final = AdaBoostClassifier(estimator=GradientBoostingClassifier(n_estimators=5000), n_estimators=4000, learning_rate=0.01, random_state=0)
ada_final.fit(X_train, y_train)
y_pred_ada = ada_final.predict(X_test)

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_ada)

print(cm)
print("\n")
print(accuracy_score(y_test, y_pred_ada)*100)
print(f'Precision : {precision_score(y_test, y_pred_ada, average="macro")}')
print(f'Recall : {recall_score(y_test, y_pred_ada, average="macro")*100}')
print(f'F1 Score : {f1_score(y_test, y_pred_ada, average="macro")*100}')

[[1 0 0 0 0 1]
 [0 4 0 1 0 0]
 [0 1 2 0 1 0]
 [0 0 0 1 0 0]
 [0 0 0 0 4 0]
 [2 1 1 0 1 0]]


57.14285714285714
Precision : 0.47222222222222215
Recall : 63.33333333333333
F1 Score : 52.75613275613274


##PICKLE

In [23]:
# import pickle

# with open('STAI_model_Final_wBA.pkl', 'wb') as f:
#     pickle.dump(ada_final, f)

In [24]:
# import pickle

# with open('STAI_model_Final_wBA.pkl', 'rb') as f:
#     model = pickle.load(f)

# y_pred_f = model.predict([[1, 35, 0, 1, 1, 0, 1, 26.7]])
# print(y_pred_f)

In [25]:
# print(model)