##Importing the Libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

##Importing the Dataset

In [ ]:
df = pd.read_csv('/content/STAI.csv')
df = df.drop(["Subject_Id", "Name(optional)", "Body Age"], axis='columns')

In [ ]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(sampling_strategy="not majority")
X_res, y_res = ros.fit_resample(X, y)

In [ ]:
y_res

0      3
1      4
2      2
3      6
4      1
      ..
103    6
104    6
105    6
106    6
107    6
Name: RESULT, Length: 108, dtype: int64

In [ ]:
y_res.value_counts()

3    18
4    18
2    18
6    18
1    18
5    18
Name: RESULT, dtype: int64

In [ ]:
X = X_res.values
y = y_res.values

In [ ]:
X

array([['Male', 37, 'No', 'No', 'No', 'No', 'No', 24.1],
       ['Male', 47, 'No', 'No', 'No', 'Yes', 'Yes', 22.8],
       ['Female', 47, 'No', 'No', 'No', 'No', 'Yes', 28.0],
       ['Female', 35, 'No', 'No', 'No', 'No', 'No', 27.4],
       ['Female', 33, 'No', 'No', 'No', 'No', 'No', 22.6],
       ['Female', 45, 'No', 'No', 'No', 'No', 'Yes', 24.5],
       ['Female', 41, 'No', 'No', 'No', 'No', 'No', 24.5],
       ['Female', 36, 'No', 'No', 'No', 'No', 'No', 23.2],
       ['Female', 35, 'No', 'No', 'Yes', 'No', 'Yes', 25.0],
       ['Male', 38, 'Yes', 'No', 'Yes', 'No', 'No', 25.8],
       ['Male', 43, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 30.1],
       ['Male', 39, 'No', 'No', 'No', 'Yes', 'Yes', 25.4],
       ['Male', 34, 'Yes', 'No', 'Yes', 'No', 'No', 23.9],
       ['Female', 34, 'No', 'No', 'No', 'No', 'No', 22.1],
       ['Female', 29, 'No', 'No', 'Yes', 'No', 'No', 25.7],
       ['Male', 28, 'No', 'No', 'Yes', 'Yes', 'No', 24.0],
       ['Male', 28, 'No', 'No', 'Yes', 'No', 'No', 

##LabelEncoding

In [ ]:
for i in range(X.shape[0]):
  for j in range(0, 7):
    if X[i, j] == 'No' or X[i,j] == "Male":
      X[i, j] = 0
    elif X[i, j] == 'Yes' or X[i,j] == "Female":
      X[i, j] = 1

X

array([[0, 37, 0, 0, 0, 0, 0, 24.1],
       [0, 47, 0, 0, 0, 1, 1, 22.8],
       [1, 47, 0, 0, 0, 0, 1, 28.0],
       [1, 35, 0, 0, 0, 0, 0, 27.4],
       [1, 33, 0, 0, 0, 0, 0, 22.6],
       [1, 45, 0, 0, 0, 0, 1, 24.5],
       [1, 41, 0, 0, 0, 0, 0, 24.5],
       [1, 36, 0, 0, 0, 0, 0, 23.2],
       [1, 35, 0, 0, 1, 0, 1, 25.0],
       [0, 38, 1, 0, 1, 0, 0, 25.8],
       [0, 43, 1, 1, 1, 0, 1, 30.1],
       [0, 39, 0, 0, 0, 1, 1, 25.4],
       [0, 34, 1, 0, 1, 0, 0, 23.9],
       [1, 34, 0, 0, 0, 0, 0, 22.1],
       [1, 29, 0, 0, 1, 0, 0, 25.7],
       [0, 28, 0, 0, 1, 1, 0, 24.0],
       [0, 28, 0, 0, 1, 0, 0, 24.3],
       [0, 29, 0, 0, 1, 1, 0, 25.0],
       [0, 30, 0, 0, 1, 0, 0, 24.6],
       [0, 34, 0, 0, 1, 1, 0, 28.4],
       [0, 35, 0, 0, 0, 1, 0, 24.3],
       [0, 39, 0, 0, 1, 0, 0, 24.3],
       [0, 30, 0, 0, 1, 1, 0, 26.8],
       [0, 45, 0, 0, 1, 0, 1, 21.2],
       [0, 36, 0, 0, 0, 1, 1, 23.8],
       [0, 28, 0, 0, 1, 0, 0, 22.0],
       [0, 41, 0, 0, 0, 1, 0, 20.9],
 

##Splitting the Dataset

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
X_train.shape

(86, 8)

In [ ]:
type(y_train)

numpy.ndarray

##Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_scaled_train = sc.fit_transform(X_train)
X_scaled_test = sc.fit_transform(X_test)

##Normalisation

In [ ]:
# from sklearn.preprocessing import Normalizer
# nl_1 = Normalizer()

# X_train_normal = nl_1.fit_transform(X_train)
# X_test_normal = nl_1.transform(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier

# for i in range(1, 20):
#   rf = RandomForestClassifier(n_estimators=i)
#   rf.fit(X_train, y_train)
#   y_pred = rf.predict(X_test)
#   cm = confusion_matrix(y_test, y_pred)
#   print(f'For {i} trees \n{cm}')
#   print(f'For {i} trees, Accuracy : {accuracy_score(y_test, y_pred)}\n\n')

In [ ]:
# from sklearn.tree import DecisionTreeClassifier
# dc = DecisionTreeClassifier()
# dc.fit(X_train, y_train)

# y_pred = dc.predict(X_test)
# cm_2 = confusion_matrix(y_test, y_pred)
# cm_2
# accuracy_score(y_test, y_pred)

In [ ]:
# from sklearn.linear_model import LogisticRegression
# lg = LogisticRegression()
# lg.fit(X_train_normal, y_train)

# y_pred = lg.predict(X_test_normal)
# cm_2 = confusion_matrix(y_test, y_pred)
# cm_2
# accuracy_score(y_test, y_pred)

In [ ]:
# from sklearn.ensemble import GradientBoostingClassifier
# for i in range(1, 20):
#   gboost = GradientBoostingClassifier(n_estimators=i)
#   gboost.fit(X_train, y_train)
#   y_pred = gboost.predict(X_test)
#   cm = confusion_matrix(y_test, y_pred)
#   print(f'For {i} trees \n{cm}')
#   print(f'For {i} trees, Accuracy : {accuracy_score(y_test, y_pred)}\n\n')

In [ ]:
# from sklearn.neighbors import KNeighborsClassifier
# knn = KNeighborsClassifier()

# knn.fit(X_scaled_train, y_train)
# y_pred = knn.predict(X_scaled_test)
# cm = confusion_matrix(y_test, y_pred)
# print(cm)
# print(f'Accuracy : {accuracy_score(y_test, y_pred)}')

# print(f'Predictions : {y_pred}')
# print(f'Results : {y_test}')

In [ ]:
X_test

array([[1, 29, 0, 0, 1, 0, 0, 25.7],
       [0, 43, 1, 1, 1, 0, 1, 30.1],
       [1, 43, 0, 0, 0, 1, 0, 26.5],
       [1, 47, 0, 0, 0, 0, 1, 28.0],
       [0, 36, 0, 0, 0, 1, 1, 23.8],
       [0, 38, 1, 0, 1, 0, 0, 25.8],
       [0, 34, 1, 0, 1, 0, 0, 23.9],
       [1, 36, 0, 0, 0, 0, 0, 23.2],
       [0, 28, 0, 0, 1, 0, 0, 24.3],
       [0, 37, 0, 0, 0, 0, 1, 23.8],
       [0, 43, 1, 1, 1, 0, 1, 30.1],
       [0, 30, 0, 0, 1, 1, 0, 26.8],
       [1, 28, 0, 0, 1, 1, 0, 26.0],
       [0, 43, 1, 1, 1, 0, 1, 30.1],
       [1, 43, 0, 0, 0, 1, 0, 26.5],
       [0, 29, 0, 0, 0, 0, 0, 20.9],
       [1, 34, 0, 0, 0, 0, 0, 22.1],
       [1, 43, 0, 0, 0, 1, 0, 26.5],
       [0, 31, 0, 0, 0, 1, 0, 19.5],
       [0, 30, 0, 0, 1, 0, 0, 29.0],
       [0, 30, 0, 0, 1, 1, 0, 26.8],
       [1, 35, 0, 0, 1, 0, 1, 25.0]], dtype=object)

In [ ]:
# from sklearn.model_selection import cross_val_score
# accuracies = cross_val_score(estimator = gboost, X = X_scaled_train, y = y_train, cv = 10)
# print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
# print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

##GBoost

In [ ]:
# from sklearn.model_selection import GridSearchCV
# from sklearn.ensemble import GradientBoostingClassifier
# gboost = GradientBoostingClassifier()

# parameters = [{'learning_rate': [0.1, 0.01], 'n_estimators': [100, 500, 1000], 'max_depth': [9]}]
# grid_search = GridSearchCV(estimator = gboost,
#                            param_grid = parameters,
#                            scoring = 'accuracy',
#                            cv = 10,
#                            n_jobs = -1)
# grid_search.fit(X_train, y_train)
# best_accuracy = grid_search.best_score_
# best_parameters = grid_search.best_params_
# print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
# print("Best Parameters:", best_parameters)

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, f1_score, recall_score
gboost_final = GradientBoostingClassifier(n_estimators = 750, learning_rate=0.01, max_depth=9)
gboost_final.fit(X_train, y_train)

y_pred_gb = gboost_final.predict(X_test)
cm = confusion_matrix(y_test, y_pred_gb)

print(cm)
print("\n")
print(f'Accuracy : {accuracy_score(y_test, y_pred_gb)}')
print(f'Precision : {precision_score(y_test, y_pred_gb, average="macro")}')
print(f'F1 Score : {f1_score(y_test, y_pred_gb, average="macro")*100}')
print(f'Recall : {recall_score(y_test, y_pred_gb, average="macro")*100}')

[[4 0 0 0 0 0]
 [0 6 0 0 0 0]
 [0 0 0 0 1 1]
 [0 0 0 4 0 0]
 [0 0 0 0 1 0]
 [0 0 1 1 0 3]]


Accuracy : 0.8181818181818182
Precision : 0.6749999999999999
F1 Score : 70.37037037037037
Recall : 76.66666666666666


In [ ]:
# from sklearn.ensemble import GradientBoostingClassifier
# from sklearn.model_selection import cross_val_score
# gboost2 = GradientBoostingClassifier(n_estimators=100, learning_rate=0.01, min_samples_split=15)
# accuracies = cross_val_score(estimator = gboost2, X = X_train, y = y_train, cv = 10)
# print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
# print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [ ]:
# from sklearn.ensemble import GradientBoostingClassifier
# from sklearn.model_selection import cross_val_score
# gboost2 = GradientBoostingClassifier(n_estimators=10000, learning_rate=0.01)
# accuracies = cross_val_score(estimator = gboost2, X = X_train, y = y_train, cv = 10)
# print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
# print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

##RandomForest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
rforest = RandomForestClassifier()

parameters = [{'criterion': ['gini', 'entropy', 'log_loss'], 'n_estimators': [500, 600, 700, 800, 900]}]
grid_search = GridSearchCV(estimator = rforest,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

Best Accuracy: 60.83 %
Best Parameters: {'criterion': 'gini', 'n_estimators': 600}


In [ ]:
# from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, f1_score, recall_score
# rforest_final = RandomForestClassifier(n_estimators = 500, criterion='gini')
# rforest_final.fit(X_train, y_train)

# y_pred_rf = rforest_final.predict(X_test)
# cm = confusion_matrix(y_test, y_pred_gb)

# print(cm)
# print("\n")
# print(f'Accuracy : {accuracy_score(y_test, y_pred_rf)}')
# print(f'Precision : {precision_score(y_test, y_pred_rf, average="macro")}')
# print(f'F1 Score : {f1_score(y_test, y_pred_rf, average="macro")*100}')
# print(f'Recall : {recall_score(y_test, y_pred_rf, average="macro")*100}')

In [ ]:
# from sklearn.ensemble import ExtraTreesClassifier
# etrees = ExtraTreesClassifier()

# parameters = [{'n_estimators': [1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000]}]
# grid_search = GridSearchCV(estimator = etrees,
#                            param_grid = parameters,
#                            scoring = 'accuracy',
#                            cv = 10,
#                            n_jobs = -1)
# grid_search.fit(X_train, y_train)
# best_accuracy = grid_search.best_score_
# best_parameters = grid_search.best_params_
# print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
# print("Best Parameters:", best_parameters)

In [ ]:
# eforest2 = ExtraTreesClassifier(n_estimators=2000)
# accuracies = cross_val_score(estimator = eforest2, X = X_train, y = y_train, cv = 10)
# print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
# print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
svc = SVC()

parameters = [{'C' : [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 'kernel' : ['linear', 'poly', 'rbf', 'sigmoid']}]
grid_search = GridSearchCV(estimator = svc,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search.fit(X_scaled_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

Best Accuracy: 51.67 %
Best Parameters: {'C': 1.0, 'kernel': 'rbf'}


In [ ]:
# svc2 = SVC(C=0.8, kernel='poly', degree=9)
# accuracies = cross_val_score(estimator = svc2, X = X_scaled_train, y = y_train, cv = 10)
# print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
# print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [ ]:
# from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, f1_score, recall_score
# svc_final = SVC(C=0.5, kernel='linear')
# svc_final.fit(X_scaled_train, y_train)

# y_pred_svc = svc_final.predict(X_scaled_test)
# cm = confusion_matrix(y_test, y_pred_svc)

# print(cm)
# print("\n")
# print(f'Accuracy : {accuracy_score(y_test, y_pred_svc)}')
# print(f'Precision : {precision_score(y_test, y_pred_svc, average="macro")}')
# print(f'Recall : {recall_score(y_test, y_pred_svc, average="macro")*100}')
# print(f'F1 Score : {f1_score(y_test, y_pred_svc, average="macro")*100}')

##Catboost

In [ ]:
!pip install catboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from catboost import CatBoostClassifier
cboost = CatBoostClassifier()

parameters = [{'n_estimators': [1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000]}]
grid_search = GridSearchCV(estimator = cboost,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py:700: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(


Learning rate set to 0.06982
0:	learn: 1.7554733	total: 47.8ms	remaining: 47.7s
1:	learn: 1.7221858	total: 49.1ms	remaining: 24.5s
2:	learn: 1.6960047	total: 50.6ms	remaining: 16.8s
3:	learn: 1.6667798	total: 52.1ms	remaining: 13s
4:	learn: 1.6332203	total: 53.7ms	remaining: 10.7s
5:	learn: 1.6054660	total: 55.3ms	remaining: 9.16s
6:	learn: 1.5719573	total: 57ms	remaining: 8.09s
7:	learn: 1.5445349	total: 58.7ms	remaining: 7.27s
8:	learn: 1.5178678	total: 60.3ms	remaining: 6.63s
9:	learn: 1.4867316	total: 65.1ms	remaining: 6.44s
10:	learn: 1.4675791	total: 66.7ms	remaining: 6s
11:	learn: 1.4426866	total: 69.5ms	remaining: 5.72s
12:	learn: 1.4196184	total: 72.5ms	remaining: 5.51s
13:	learn: 1.3943322	total: 75.1ms	remaining: 5.29s
14:	learn: 1.3710331	total: 77.9ms	remaining: 5.12s
15:	learn: 1.3521497	total: 79.9ms	remaining: 4.92s
16:	learn: 1.3295646	total: 81.2ms	remaining: 4.7s
17:	learn: 1.3092962	total: 82.8ms	remaining: 4.52s
18:	learn: 1.2895816	total: 84.3ms	remaining: 4.35s
1

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, f1_score, recall_score
cat_final = CatBoostClassifier(n_estimators=2000)
cat_final.fit(X_train, y_train)

y_pred_cat = cat_final.predict(X_test)
cm = confusion_matrix(y_test, y_pred_cat)

print(cm)
print("\n")
print(f'Accuracy : {accuracy_score(y_test, y_pred_cat)}')
print(f'Precision : {precision_score(y_test, y_pred_cat, average="macro")}')
print(f'Recall : {recall_score(y_test, y_pred_cat, average="macro")*100}')
print(f'F1 Score : {f1_score(y_test, y_pred_cat, average="macro")*100}')

Learning rate set to 0.03887
0:	learn: 1.7714785	total: 1.43ms	remaining: 2.86s
1:	learn: 1.7525264	total: 2.75ms	remaining: 2.75s
2:	learn: 1.7373347	total: 3.98ms	remaining: 2.65s
3:	learn: 1.7203071	total: 5.26ms	remaining: 2.62s
4:	learn: 1.7004682	total: 6.95ms	remaining: 2.77s
5:	learn: 1.6835262	total: 11.1ms	remaining: 3.67s
6:	learn: 1.6631645	total: 12.3ms	remaining: 3.5s
7:	learn: 1.6428095	total: 16.8ms	remaining: 4.17s
8:	learn: 1.6258872	total: 18.1ms	remaining: 4s
9:	learn: 1.6058433	total: 19.3ms	remaining: 3.85s
10:	learn: 1.5889689	total: 24ms	remaining: 4.35s
11:	learn: 1.5726759	total: 32.8ms	remaining: 5.43s
12:	learn: 1.5574174	total: 34.7ms	remaining: 5.31s
13:	learn: 1.5406471	total: 37.6ms	remaining: 5.33s
14:	learn: 1.5249120	total: 45.5ms	remaining: 6.02s
15:	learn: 1.5118010	total: 48.2ms	remaining: 5.98s
16:	learn: 1.4961310	total: 50.9ms	remaining: 5.93s
17:	learn: 1.4823470	total: 58.1ms	remaining: 6.39s
18:	learn: 1.4684074	total: 59.6ms	remaining: 6.22s

##Ensemble (GBOOST + RFOREST + ADABOOST + KNN + SVM + XGBOOST)

Write the most accurate model

In [ ]:
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import RandomForestClassifier


best_gboost = GradientBoostingClassifier(n_estimators=1000, learning_rate=0.3)
best_rforest = RandomForestClassifier(n_estimators=780)


estimators = [('gboost', best_gboost), ('rf', best_rforest)]
ensemble_1 = VotingClassifier(estimators, voting='hard')
ensemble_2 = VotingClassifier(estimators, voting='hard')

ensemble_1.fit(X_train, y_train)
ensemble_2.fit(X_scaled_train, y_train)

print(f'Simple Train : {ensemble_1.score(X_test, y_test)}')
print(f'Scaled Train : {ensemble_2.score(X_scaled_test, y_test)}')

##ADABoost

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import AdaBoostClassifier
ada = AdaBoostClassifier()

parameters = [{'estimator': [RandomForestClassifier(), GradientBoostingClassifier()], 'n_estimators': [1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000]}]
grid_search = GridSearchCV(estimator = ada,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

Best Accuracy: 65.28 %
Best Parameters: {'estimator': GradientBoostingClassifier(), 'n_estimators': 5000}


In [ ]:
# from sklearn.model_selection import GridSearchCV
# from sklearn.ensemble import RandomForestClassifier
# ada = AdaBoostClassifier()

# parameters = [{'estimator': [AdaBoostClassifier(estimator=RandomForestClassifier(n_estimators=5000), n_estimators=10000, learning_rate=0.01)], 'n_estimators': [10, 50, 100, 500, 1000, 2000, 5000], 'learning_rate' : [0.1, 0.01, 0.001]}]
# grid_search = GridSearchCV(estimator = ada,
#                            param_grid = parameters,
#                            scoring = 'accuracy',
#                            cv = 10,
#                            n_jobs = -1)
# grid_search.fit(X_train, y_train)
# best_accuracy = grid_search.best_score_
# best_parameters = grid_search.best_params_
# print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
# print("Best Parameters:", best_parameters)

In [ ]:
# from sklearn.ensemble import AdaBoostClassifier
# from sklearn.ensemble import GradientBoostingClassifier
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.model_selection import cross_val_score

# ada2 = AdaBoostClassifier(estimator=GradientBoostingClassifier(n_estimators=5000), n_estimators=10000, learning_rate=0.01, random_state=0)
# accuracies = cross_val_score(estimator = ada2, X = X_train, y = y_train, cv = 6)
# print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
# print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [ ]:
# accuracies

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier

ada_final = AdaBoostClassifier(estimator=GradientBoostingClassifier(n_estimators=5000), n_estimators=4000, learning_rate=0.01, random_state=0)
ada_final.fit(X_train, y_train)
y_pred_ada = ada_final.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_ada)

print(cm)
print("\n")
print(accuracy_score(y_test, y_pred_ada)*100)
print(f'Precision : {precision_score(y_test, y_pred_ada, average="macro")}')
print(f'Recall : {recall_score(y_test, y_pred_ada, average="macro")*100}')
print(f'F1 Score : {f1_score(y_test, y_pred_ada, average="macro")*100}')

[[4 0 0 0 0 0]
 [0 6 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 1 0]
 [0 0 0 1 0 4]]


95.45454545454545
Precision : 0.9666666666666667
Recall : 96.66666666666667
F1 Score : 96.29629629629632


In [ ]:
X_test

array([[1, 29, 0, 0, 1, 0, 0, 25.7],
       [0, 43, 1, 1, 1, 0, 1, 30.1],
       [1, 43, 0, 0, 0, 1, 0, 26.5],
       [1, 47, 0, 0, 0, 0, 1, 28.0],
       [0, 36, 0, 0, 0, 1, 1, 23.8],
       [0, 38, 1, 0, 1, 0, 0, 25.8],
       [0, 34, 1, 0, 1, 0, 0, 23.9],
       [1, 36, 0, 0, 0, 0, 0, 23.2],
       [0, 28, 0, 0, 1, 0, 0, 24.3],
       [0, 37, 0, 0, 0, 0, 1, 23.8],
       [0, 43, 1, 1, 1, 0, 1, 30.1],
       [0, 30, 0, 0, 1, 1, 0, 26.8],
       [1, 28, 0, 0, 1, 1, 0, 26.0],
       [0, 43, 1, 1, 1, 0, 1, 30.1],
       [1, 43, 0, 0, 0, 1, 0, 26.5],
       [0, 29, 0, 0, 0, 0, 0, 20.9],
       [1, 34, 0, 0, 0, 0, 0, 22.1],
       [1, 43, 0, 0, 0, 1, 0, 26.5],
       [0, 31, 0, 0, 0, 1, 0, 19.5],
       [0, 30, 0, 0, 1, 0, 0, 29.0],
       [0, 30, 0, 0, 1, 1, 0, 26.8],
       [1, 35, 0, 0, 1, 0, 1, 25.0]], dtype=object)

In [ ]:
test_model = GradientBoostingClassifier(n_estimators=5000)
test_model.fit(X_train, y_train)

important_test = test_model.feature_importances_
for i,v in enumerate(important_test):
 print('Feature: %0d, Score: %.5f' % (i,v))

Feature: 0, Score: 0.06676
Feature: 1, Score: 0.26352
Feature: 2, Score: 0.04428
Feature: 3, Score: 0.00050
Feature: 4, Score: 0.01833
Feature: 5, Score: 0.02944
Feature: 6, Score: 0.02166
Feature: 7, Score: 0.55551


In [ ]:
y_test  # 4

array([4, 1, 2, 2, 6, 5, 6, 4, 3, 4, 1, 6, 2, 1, 2, 3, 2, 2, 4, 1, 6, 6])

In [ ]:
coefs = []
for clf,w in zip(ada_final.estimators_,ada_final.estimator_weights_):
    coefs.append(clf.feature_importances_*w)
coefs = np.array(coefs).mean(axis=0)
print(coefs*100)

[6.47178770e+00 2.61444668e+01 4.51385155e+00 4.02738268e-02
 1.91857455e+00 3.29212572e+00 2.28342212e+00 5.53354977e+01]


In [ ]:
coef_final = coefs
y_maths = []
for i in range(len(X[:, 1])):
  y_maths.append(((coef_final[0]*X[i,0]) + (coef_final[1]*X[i,1])+ (coef_final[2]*X[i,2]) + (coef_final[3]*X[i,3]) + (coef_final[4] * X[i,4]) + (coef_final[5]*X[i,5]) + (coef_final[6]*X[i,6]) + (coef_final[7]*X[i,7])))

print(f"Y Actual : {y}\n")
print(f"Y Pred : {y_maths}")

Y Actual : [3 4 2 6 1 6 3 4 6 5 1 3 6 2 4 5 3 6 3 6 6 6 6 1 6 5 3 4 6 3 2 3 4 4 6 4 3
 4 1 2 3 2 6 3 3 2 3 3 4 4 3 2 3 3 1 4 3 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2
 2 2 2 2 2 2 2 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 6 6 6 6 6]

Y Pred : [23.009307668300693, 24.96014835451807, 27.86939085728654, 24.37720763529626, 21.198214407638172, 25.40975910036085, 24.341146207754775, 22.31456139771467, 23.091175655999017, 24.27578005892532, 27.985666760852915, 24.30731395309053, 22.178626930254882, 21.182981586756483, 21.887021911910377, 20.653077162482973, 20.78616239855446, 21.467876807830972, 21.47505822752348, 24.65650707059264, 22.63001058524935, 23.662053745031415, 22.72536043516814, 23.53815554315255, 22.637611985527577, 19.513445950335605, 22.317271668964636, 21.82419970318881, 22.065375711509866, 21.721015418664436, 25.497507550001416, 19.376095906561517, 21.401183407384032, 18.1795435627511, 19.959668461765986, 17.79804552012758, 21.274073220766198, 20.609792591943553, 22.545566788421

In [ ]:
# from sklearn.ensemble import RandomForestClassifier
# rf = RandomForestClassifier(n_estimators=2)
# rf.fit(X_train, y_train)

# individual_trees = rf.estimators_

# for i in range(2):
#   tree_0_feature_importances = individual_trees[i].feature_importances_
#   print(tree_0_feature_importances)
#   print("\n\n")

##PICKLE

In [ ]:
import pickle

with open('STAI_model_Final_wBA.pkl', 'wb') as f:
    pickle.dump(ada_final, f)

In [1]:
import pickle

with open('STAI_model_Final_wBA.pkl', 'rb') as f:
    model = pickle.load(f)

y_pred_f = model.predict([[1, 35, 0, 1, 1, 0, 1, 26.7]])
print(y_pred_f)

[6]


In [ ]:
# print(model)

|
##ROC - CAP

In [ ]:
# from sklearn.ensemble import VotingClassifier
# from sklearn.ensemble import RandomForestClassifier


# best_gboost = GradientBoostingClassifier(n_estimators=1000, learning_rate=0.3)
# best_ada = AdaBoostClassifier(GradientBoostingClassifier(n_estimators=1000, learning_rate=0.3), n_estimators=4000)


# estimators = [('gboost', best_gboost), ('ada', best_ada)]
# ensemble_1 = VotingClassifier(estimators, voting='hard')
# ensemble_2 = VotingClassifier(estimators, voting='hard')

# ensemble_1.fit(X_train, y_train)
# ensemble_2.fit(X_scaled_train, y_train)

# print(f'Simple Train : {ensemble_1.score(X_test, y_test)}')
# print(f'Scaled Train : {ensemble_2.score(X_scaled_test, y_test)}')

##XGBoost

In [ ]:
import xgboost as xgb

In [ ]:
from sklearn.model_selection import GridSearchCV
xgb_model = xgb.XGBClassifier()
parameters = [{'n_estimators': [10, 50, 100, 500, 1000, 1500, 2000], 'learning_rate' : [0.1, 0.01, 0.001], 'tree_method' : ['approx', 'hist']}]
grid_search = GridSearchCV(estimator = xgb_model,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search.fit(X_scaled_train, (y_train - 1))
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

Best Accuracy: 65.28 %
Best Parameters: {'learning_rate': 0.1, 'n_estimators': 500, 'tree_method': 'approx'}


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, f1_score, recall_score
xgb_model = xgb.XGBClassifier(n_estimators=500, learning_rate=0.1, tree_method="approx")
xgb_model.fit(X_train, (y_train-1))

y_pred_xgb = xgb_model.predict(X_test)
cm = confusion_matrix((y_test-1), y_pred_xgb)

print(cm)
print("\n")
print(f'Accuracy : {accuracy_score(y_test-1, y_pred_xgb)}')
print(f'Precision : {precision_score(y_test-1, y_pred_xgb, average="macro")}')
print(f'Recall : {recall_score(y_test-1, y_pred_xgb, average="macro")*100}')
print(f'F1 Score : {f1_score(y_test-1, y_pred_xgb, average="macro")*100}')

[[4 0 0 0 0 0]
 [0 6 0 0 0 0]
 [0 1 1 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 1 0]
 [0 1 0 1 0 3]]


Accuracy : 0.8636363636363636
Precision : 0.9249999999999999
Recall : 85.0
F1 Score : 86.04497354497354


In [ ]:
# from sklearn.model_selection import cross_val_score
# xg_model2 = xgb.XGBClassifier(n_estimators=10, learning_rate=0.1, tree_methods='approx')
# accuracies = cross_val_score(estimator = xg_model2, X = X_scaled_train, y = (y_train-1), cv = 10)
# print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
# print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))
















##SMOTE

In [ ]:
# import imblearn
# from imblearn.over_sampling import SMOTE
# oversample = SMOTE(random_state=42)

# X_smote, y_smote = oversample.fit_resample(X, y)

##BalancedBaggingClassifier

In [ ]:
# from imblearn.ensemble import BalancedBaggingClassifier
# from sklearn.model_selection import GridSearchCV
# bag = BalancedBaggingClassifier()
# parameters = [{'n_estimators': [10, 50, 100, 500, 1000, 2000]}]
# grid_search = GridSearchCV(estimator = bag,
#                            param_grid = parameters,
#                            scoring = 'accuracy',
#                            cv = 10,
#                            n_jobs = -1)
# grid_search.fit(X_train, y_train)
# best_accuracy = grid_search.best_score_
# best_parameters = grid_search.best_params_
# print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
# print("Best Parameters:", best_parameters)

##LightGBM

In [ ]:
# pip install lightgbm

In [ ]:
# import lightgbm as lgb
# train_model = lgb.Dataset(X_train, label=y_train)

In [ ]:
# params = {'num_leaves':1000, 'objective': 'multiclass'}
# num_rounds = 100
# bst = lgb.train(params, train_model, num_rounds)