##Importing the Libraries

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

##Importing the Dataset

In [ ]:
df = pd.read_csv('/content/final_data_RMSSD.csv')
df.drop('ID', axis=1 , inplace=True)

In [ ]:
df.head()

Gender  Age Alchohol Smoking Non-Veg Exercise         Medication   BMI  \
0    Male   37       No      No      No       No                 No  24.1   
1    Male   47       No      No      No      Yes  Yes(Anxiety/B.P.)  22.8   
2  Female   47       No      No      No       No       Yes(Thyroid)  28.0   
3  Female   35       No      No      No       No                 No  27.4   
4  Female   33       No      No      No       No                 No  22.6   

   rmssd_best  
0           2  
1           2  
2           2  
3           2  
4           3

In [ ]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(sampling_strategy="not majority")
X_res, y_res = ros.fit_resample(X, y)

In [ ]:
y_res

0     2
1     2
2     2
3     2
4     3
     ..
79    5
80    5
81    5
82    5
83    5
Name: rmssd_best, Length: 84, dtype: int64

In [ ]:
y_res.value_counts()

2    14
3    14
5    14
4    14
1    14
6    14
Name: rmssd_best, dtype: int64

In [ ]:
X = X_res.values
y = y_res.values

In [ ]:
X

array([['Male', 37, 'No', 'No', 'No', 'No', 'No', 24.1],
       ['Male', 47, 'No', 'No', 'No', 'Yes', 'Yes(Anxiety/B.P.)', 22.8],
       ['Female', 47, 'No', 'No', 'No', 'No', 'Yes(Thyroid)', 28.0],
       ['Female', 35, 'No', 'No', 'No', 'No', 'No', 27.4],
       ['Female', 33, 'No', 'No', 'No', 'No', 'No', 22.6],
       ['Female', 45, 'No', 'No', 'No', 'No', 'Yes(B.P.)', 24.5],
       ['Female', 41, 'No', 'No', 'No', 'No', 'No', 24.5],
       ['Female', 36, 'No', 'No', 'No', 'No', 'No', 23.2],
       ['Female', 35, 'No', 'No', 'Yes', 'No', 'Yes(Thyroid)', 25.0],
       ['Male', 38, 'Yes', 'No', 'Yes', 'No', 'No', 25.8],
       ['Male', 43, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 30.1],
       ['Male', 39, 'No', 'No', 'No', 'Yes', 'Yes', 25.4],
       ['Male', 34, 'Yes', 'No', 'Yes', 'No', 'No', 23.9],
       ['Female', 34, 'No', 'No', 'No', 'No', 'No', 22.1],
       ['Female', 29, 'No', 'No', 'Yes', 'No', 'No', 25.7],
       ['Male', 28, 'No', 'No', 'Yes', 'Yes', 'No', 24.0],
       ['Male

##LabelEncoding

In [ ]:
for i in range(X.shape[0]):
  for j in range(0, 6):
    if X[i, j] == 'No' or X[i,j] == "Male" or X[i, j] == 'No ':
      X[i, j] = 0
    elif X[i, j] == 'Yes' or X[i,j] == "Female":
      X[i, j] = 1

for i in range(X.shape[0]):
  for j in range(6,7):
    if X[i,j] == 'No':
      X[i,j] = 0
    else:
      X[i,j] = 1
X

array([[0, 37, 0, 0, 0, 0, 0, 24.1],
       [0, 47, 0, 0, 0, 1, 1, 22.8],
       [1, 47, 0, 0, 0, 0, 1, 28.0],
       [1, 35, 0, 0, 0, 0, 0, 27.4],
       [1, 33, 0, 0, 0, 0, 0, 22.6],
       [1, 45, 0, 0, 0, 0, 1, 24.5],
       [1, 41, 0, 0, 0, 0, 0, 24.5],
       [1, 36, 0, 0, 0, 0, 0, 23.2],
       [1, 35, 0, 0, 1, 0, 1, 25.0],
       [0, 38, 1, 0, 1, 0, 0, 25.8],
       [0, 43, 1, 1, 1, 0, 1, 30.1],
       [0, 39, 0, 0, 0, 1, 1, 25.4],
       [0, 34, 1, 0, 1, 0, 0, 23.9],
       [1, 34, 0, 0, 0, 0, 0, 22.1],
       [1, 29, 0, 0, 1, 0, 0, 25.7],
       [0, 28, 0, 0, 1, 1, 0, 24.0],
       [0, 28, 0, 0, 1, 0, 0, 24.3],
       [0, 29, 0, 0, 1, 1, 0, 25.0],
       [0, 30, 0, 0, 1, 0, 0, 24.6],
       [0, 34, 0, 0, 1, 1, 0, 28.4],
       [0, 35, 0, 0, 0, 1, 0, 24.3],
       [0, 39, 0, 0, 1, 0, 0, 24.3],
       [0, 30, 0, 0, 1, 1, 0, 26.8],
       [0, 45, 0, 0, 1, 0, 1, 21.2],
       [0, 36, 0, 0, 0, 1, 1, 23.8],
       [0, 28, 0, 0, 1, 0, 0, 22.0],
       [0, 41, 0, 0, 0, 1, 0, 20.9],
 

##Splitting the Dataset

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
X_train.shape

(67, 8)

##Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.fit_transform(X_test)

##Normalisation

In [15]:
from sklearn.preprocessing import Normalizer
nl_1 = Normalizer()

X_train_normal = nl_1.fit_transform(X_train)
X_test_normal = nl_1.transform(X_test)

#MODELS

In [16]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier, BaggingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.neural_network import MLPClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

In [17]:
# Function to print evaluation metrics
def print_metrics(y_true, y_pred):
    accuracy = accuracy_score(y_true, y_pred)
    precision_micro = precision_score(y_true, y_pred, average='micro')
    recall_micro = recall_score(y_true, y_pred, average='micro')
    f1_micro = f1_score(y_true, y_pred, average='micro')

    precision_macro = precision_score(y_true, y_pred, average='macro')
    recall_macro = recall_score(y_true, y_pred, average='macro')
    f1_macro = f1_score(y_true, y_pred, average='macro')

    precision_weighted = precision_score(y_true, y_pred, average='weighted')
    recall_weighted = recall_score(y_true, y_pred, average='weighted')
    f1_weighted = f1_score(y_true, y_pred, average='weighted')

    print(f"Accuracy: {accuracy:.10f}")
    print("\nMicro-average:")
    print(f"Precision: {precision_micro:.10f}")
    print(f"Recall: {recall_micro:.10f}")
    print(f"F1 Score: {f1_micro:.10f}")

    print("\nMacro-average:")
    print(f"Precision: {precision_macro:.10f}")
    print(f"Recall: {recall_macro:.10f}")
    print(f"F1 Score: {f1_macro:.10f}")

    print("\nWeighted-average:")
    print(f"Precision: {precision_weighted:.10f}")
    print(f"Recall: {recall_weighted:.10f}")
    print(f"F1 Score: {f1_weighted:.10f}")

In [ ]:
import warnings
warnings.filterwarnings("ignore")

###Logistic Regression

In [ ]:
lr = LogisticRegression()
lr_params = {
    'penalty': ['l1', 'l2'],
    'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000],
    'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],
    'max_iter': [50, 100, 200, 500, 1000],
    'class_weight': [None, 'balanced'],
    'random_state': [42]
}
grid_lr = GridSearchCV(lr, lr_params, cv=5)
grid_lr.fit(X_train_scaled, y_train)
y_pred_lr = grid_lr.predict(X_test_scaled)

# Print details of the Logistic Regression model
print("Logistic Regression:")
print("Best Parameters:", grid_lr.best_params_)
print("Best Score:", grid_lr.best_score_* 100 )
print_metrics(y_test, y_pred_lr)
print("\n")

Logistic Regression:
Best Parameters: {'C': 0.001, 'class_weight': None, 'max_iter': 50, 'penalty': 'l2', 'random_state': 42, 'solver': 'liblinear'}
Best Score: 32.747252747252745
Accuracy: 0.2352941176

Micro-average:
Precision: 0.2352941176
Recall: 0.2352941176
F1 Score: 0.2352941176

Macro-average:
Precision: 0.1944444444
Recall: 0.2361111111
F1 Score: 0.2115079365

Weighted-average:
Precision: 0.2009803922
Recall: 0.2352941176
F1 Score: 0.2151260504




##KNeighbors

In [ ]:
knn = KNeighborsClassifier()
knn_params = {
    'n_neighbors': [3, 5, 7, 9, 11, 15, 20],
    'weights': ['uniform', 'distance'],
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'leaf_size': [30, 40, 50, 60],
    'p': [1, 2]
}
grid_knn = GridSearchCV(knn, knn_params, cv=5)
grid_knn.fit(X_train_scaled, y_train)
y_pred_knn = grid_knn.predict(X_test_scaled)

# Print details of the k-Nearest Neighbors model
print("k-Nearest Neighbors:")
print("Best Parameters:", grid_knn.best_params_)
print("Best Score:", grid_knn.best_score_)
print_metrics(y_test, y_pred_knn)
print("\n")

k-Nearest Neighbors:
Best Parameters: {'algorithm': 'auto', 'leaf_size': 30, 'n_neighbors': 5, 'p': 2, 'weights': 'distance'}
Best Score: 0.5054945054945055
Accuracy: 0.2941176471

Micro-average:
Precision: 0.2941176471
Recall: 0.2941176471
F1 Score: 0.2941176471

Macro-average:
Precision: 0.2500000000
Recall: 0.3333333333
F1 Score: 0.2777777778

Weighted-average:
Precision: 0.2352941176
Recall: 0.2941176471
F1 Score: 0.2549019608




##SVC

In [ ]:
svm = SVC()
svm_params = {
    'C': [0.1, 1, 10, 100, 1000],
    'kernel': ['linear', 'rbf', 'poly', 'sigmoid'],
    'gamma': ['scale', 'auto', 0.1, 1, 10, 100],
    'degree': [2, 3, 4],
    'coef0': [0.0, 0.5, 1.0]
}

grid_svm = GridSearchCV(svm, svm_params, cv=5)
grid_svm.fit(X_train_scaled, y_train)
y_pred_svm = grid_svm.predict(X_test_scaled)

# Print details of the Support Vector Machines model
print("Support Vector Machines:")
print("Best Parameters:", grid_svm.best_params_)
print("Best Score:", grid_svm.best_score_)
print_metrics(y_test, y_pred_svm)
print("\n")


Support Vector Machines:
Best Parameters: {'C': 10, 'coef0': 1.0, 'degree': 2, 'gamma': 1, 'kernel': 'poly'}
Best Score: 0.4758241758241758
Accuracy: 0.5882352941

Micro-average:
Precision: 0.5882352941
Recall: 0.5882352941
F1 Score: 0.5882352941

Macro-average:
Precision: 0.5138888889
Recall: 0.5833333333
F1 Score: 0.5158730159

Weighted-average:
Precision: 0.5735294118
Recall: 0.5882352941
F1 Score: 0.5462184874




##Decision Trees

In [ ]:
dt = DecisionTreeClassifier()
dt_params = {
    'criterion': ['gini', 'entropy'],
    'splitter': ['best', 'random'],
    'max_depth': [None, 5, 10, 20, 30, 50, 100],
    'min_samples_split': [2, 5, 10, 20, 30, 50],
    'min_samples_leaf': [1, 2, 4, 8, 10, 20]
}

grid_dt = GridSearchCV(dt, dt_params, cv=5)
grid_dt.fit(X_train, y_train)
y_pred_dt = grid_dt.predict(X_test)

# Print details of the Decision Trees model
print("Decision Trees:")
print("Best Parameters:", grid_dt.best_params_)
print("Best Score:", grid_dt.best_score_)
print_metrics(y_test, y_pred_dt)
print("\n")


Decision Trees:
Best Parameters: {'criterion': 'gini', 'max_depth': 30, 'min_samples_leaf': 1, 'min_samples_split': 2, 'splitter': 'random'}
Best Score: 0.5087912087912089
Accuracy: 0.5882352941

Micro-average:
Precision: 0.5882352941
Recall: 0.5882352941
F1 Score: 0.5882352941

Macro-average:
Precision: 0.6000000000
Recall: 0.5972222222
F1 Score: 0.4952380952

Weighted-average:
Precision: 0.6705882353
Recall: 0.5882352941
F1 Score: 0.5142857143




##Random Forest

In [ ]:
rf = RandomForestClassifier()
rf_params = {
    'n_estimators': [50, 100, 200, 400, 800],
    'criterion': ['gini'],
    'max_depth': [None, 5, 10, 20,50],
    'min_samples_leaf': [1, 2, 4, 8]
}
grid_rf = GridSearchCV(rf, rf_params, cv=5)
grid_rf.fit(X_train, y_train)
y_pred_rf = grid_rf.predict(X_test)

# Print details of the Random Forest model
print("Random Forest:")
print("Best Parameters:", grid_rf.best_params_)
print("Best Score:", grid_rf.best_score_)
print_metrics(y_test, y_pred_rf)
print("\n")

Random Forest:
Best Parameters: {'criterion': 'gini', 'max_depth': 5, 'min_samples_leaf': 1, 'n_estimators': 100}
Best Score: 0.4758241758241759
Accuracy: 0.5294117647

Micro-average:
Precision: 0.5294117647
Recall: 0.5294117647
F1 Score: 0.5294117647

Macro-average:
Precision: 0.5277777778
Recall: 0.5277777778
F1 Score: 0.4952380952

Weighted-average:
Precision: 0.5882352941
Recall: 0.5294117647
F1 Score: 0.5243697479




##Gradient Boosting

In [ ]:
# gb = GradientBoostingClassifier()
# gb_params = {
#     'n_estimators': [50, 100, 200, 400, 800],
#     'learning_rate': [0.001, 0.01, 0.1, 0.2, 0.5],
#     'max_depth': [3, 5, 7, 9],
#     'min_samples_split': [2, 5, 10, 20, 30],
#     'min_samples_leaf': [1, 2, 4, 8],
# }
# grid_gb = GridSearchCV(gb, gb_params, cv=5)
# grid_gb.fit(X_train, y_train)
# y_pred_gb = grid_gb.predict(X_test)

# # Print details of the Gradient Boosting model
# print("Gradient Boosting:")
# print("Best Parameters:", grid_gb.best_params_)
# print("Best Score:", grid_gb.best_score_)
# print_metrics(y_test, y_pred_gb)
# print("\n")

##AdaBoost

In [ ]:
ada = AdaBoostClassifier()
ada_params = {
    'n_estimators': [50, 100, 200, 400, 800],
    'learning_rate': [0.001, 0.01, 0.1, 0.2, 0.5],
}
grid_ada = GridSearchCV(ada, ada_params, cv=5)
grid_ada.fit(X_train, y_train)
y_pred_ada = grid_ada.predict(X_test)

# Print details of the AdaBoost model
print("AdaBoost:")
print("Best Parameters:", grid_ada.best_params_)
print("Best Score:", grid_ada.best_score_)
print_metrics(y_test, y_pred_ada)
print("\n")


AdaBoost:
Best Parameters: {'learning_rate': 0.2, 'n_estimators': 100}
Best Score: 0.29780219780219774
Accuracy: 0.3529411765

Micro-average:
Precision: 0.3529411765
Recall: 0.3529411765
F1 Score: 0.3529411765

Macro-average:
Precision: 0.2904761905
Recall: 0.2916666667
F1 Score: 0.2777777778

Weighted-average:
Precision: 0.3428571429
Recall: 0.3529411765
F1 Score: 0.3333333333




##BaggingClassifier

In [18]:
bag = BaggingClassifier()
bag_params = {
    'n_estimators': [50, 100, 200, 400, 800],
    'max_samples': [0.1, 0.5, 1.0],
    'max_features': [0.1, 0.5, 1.0],
}
grid_bag = GridSearchCV(bag, bag_params, cv=5)
grid_bag.fit(X_train, y_train)
y_pred_bag = grid_bag.predict(X_test)

# Print details of the Bagging model
print("Bagging:")
print("Best Parameters:", grid_bag.best_params_)
print("Best Score:", grid_bag.best_score_)
print_metrics(y_test, y_pred_bag)
print("\n")

Bagging:
Best Parameters: {'max_features': 1.0, 'max_samples': 1.0, 'n_estimators': 50}
Best Score: 0.5373626373626373
Accuracy: 0.7058823529

Micro-average:
Precision: 0.7058823529
Recall: 0.7058823529
F1 Score: 0.7058823529

Macro-average:
Precision: 0.8333333333
Recall: 0.7638888889
F1 Score: 0.7035714286

Weighted-average:
Precision: 0.8588235294
Recall: 0.7058823529
F1 Score: 0.6760504202




##Gaussian Naive Bayes

In [ ]:
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred_gnb = gnb.predict(X_test)

# Print details of the Gaussian Naive Bayes model
print("Gaussian Naive Bayes:")
print_metrics(y_test, y_pred_gnb)
print("\n")

Gaussian Naive Bayes:
Accuracy: 0.4705882353

Micro-average:
Precision: 0.4705882353
Recall: 0.4705882353
F1 Score: 0.4705882353

Macro-average:
Precision: 0.2861111111
Recall: 0.5000000000
F1 Score: 0.3531135531

Weighted-average:
Precision: 0.2637254902
Recall: 0.4705882353
F1 Score: 0.3268261151




##LDA

In [ ]:
lda = LinearDiscriminantAnalysis()
lda.fit(X_train, y_train)
y_pred_lda = lda.predict(X_test)

# Print details of the Linear Discriminant Analysis model
print("Linear Discriminant Analysis:")
print_metrics(y_test, y_pred_lda)
print("\n")

Linear Discriminant Analysis:
Accuracy: 0.3529411765

Micro-average:
Precision: 0.3529411765
Recall: 0.3529411765
F1 Score: 0.3529411765

Macro-average:
Precision: 0.3611111111
Recall: 0.3472222222
F1 Score: 0.3484126984

Weighted-average:
Precision: 0.3725490196
Recall: 0.3529411765
F1 Score: 0.3563025210




##Quadratic Discriminant Analysis

In [ ]:
qda = QuadraticDiscriminantAnalysis()
qda.fit(X_train, y_train)
y_pred_qda = qda.predict(X_test)

# Print details of the Quadratic Discriminant Analysis model
print("Quadratic Discriminant Analysis:")
print_metrics(y_test, y_pred_qda)
print("\n")


Quadratic Discriminant Analysis:
Accuracy: 0.1764705882

Micro-average:
Precision: 0.1764705882
Recall: 0.1764705882
F1 Score: 0.1764705882

Macro-average:
Precision: 0.0294117647
Recall: 0.1666666667
F1 Score: 0.0500000000

Weighted-average:
Precision: 0.0311418685
Recall: 0.1764705882
F1 Score: 0.0529411765




##Multi-layer Perceptron

In [ ]:
mlp = MLPClassifier()
mlp_params = {
    'hidden_layer_sizes': [(100,), (50, 50), (100, 50), (100, 100)],
    'activation': ['relu', 'tanh', 'logistic'],
    'solver': ['adam', 'sgd'],
    'learning_rate': ['constant', 'invscaling', 'adaptive'],
    'max_iter': [100, 200, 400, 800]
}
grid_mlp = GridSearchCV(mlp, mlp_params, cv=5)
grid_mlp.fit(X_train_scaled, y_train)
y_pred_mlp = grid_mlp.predict(X_test_scaled)

# Print details of the Multi-layer Perceptron model
print("Multi-layer Perceptron (Neural Network):")
print("Best Parameters:", grid_mlp.best_params_)
print("Best Score:", grid_mlp.best_score_)
print_metrics(y_test, y_pred_mlp)
print("\n")

Multi-layer Perceptron (Neural Network):
Best Parameters: {'activation': 'logistic', 'hidden_layer_sizes': (100, 50), 'learning_rate': 'invscaling', 'max_iter': 800, 'solver': 'adam'}
Best Score: 0.49120879120879124
Accuracy: 0.3529411765

Micro-average:
Precision: 0.3529411765
Recall: 0.3529411765
F1 Score: 0.3529411765

Macro-average:
Precision: 0.4833333333
Recall: 0.3750000000
F1 Score: 0.3888888889

Weighted-average:
Precision: 0.4823529412
Recall: 0.3529411765
F1 Score: 0.3725490196




##Gaussian Process Classifier

In [ ]:
gpc = GaussianProcessClassifier()
gpc_params = {
    'kernel': [1.0 * RBF(), 2.0 * RBF()],
}
grid_gpc = GridSearchCV(gpc, gpc_params, cv=5)
grid_gpc.fit(X_train_scaled, y_train)
y_pred_gpc = grid_gpc.predict(X_test_scaled)

# Print details of the Gaussian Process Classifier model
print("Gaussian Process Classifier:")
print("Best Parameters:", grid_gpc.best_params_)
print("Best Score:", grid_gpc.best_score_)
print_metrics(y_test, y_pred_gpc)
print("\n")


Gaussian Process Classifier:
Best Parameters: {'kernel': 1**2 * RBF(length_scale=1)}
Best Score: 0.31098901098901105
Accuracy: 0.3529411765

Micro-average:
Precision: 0.3529411765
Recall: 0.3529411765
F1 Score: 0.3529411765

Macro-average:
Precision: 0.1714285714
Recall: 0.3888888889
F1 Score: 0.2369047619

Weighted-average:
Precision: 0.1579831933
Recall: 0.3529411765
F1 Score: 0.2172268908




##Dummy Classifier

In [ ]:
dummy = DummyClassifier(strategy="most_frequent")
dummy.fit(X_train, y_train)
y_pred_dummy = dummy.predict(X_test)

# Print details of the Dummy Classifier
print("Dummy Classifier:")
print_metrics(y_test, y_pred_dummy)
print("\n")

Dummy Classifier:
Accuracy: 0.1176470588

Micro-average:
Precision: 0.1176470588
Recall: 0.1176470588
F1 Score: 0.1176470588

Macro-average:
Precision: 0.0196078431
Recall: 0.1666666667
F1 Score: 0.0350877193

Weighted-average:
Precision: 0.0138408304
Recall: 0.1176470588
F1 Score: 0.0247678019




##Bagging Decision Trees

In [ ]:
bag_dt = BaggingClassifier(base_estimator=DecisionTreeClassifier())
bag_dt_params = {
    'n_estimators': [50, 100, 200, 400, 800],
    'max_samples': [0.1, 0.5, 1.0],
    'max_features': [0.1, 0.5, 1.0],
}
grid_bag_dt = GridSearchCV(bag_dt, bag_dt_params, cv=5)
grid_bag_dt.fit(X_train, y_train)
y_pred_bag_dt = grid_bag_dt.predict(X_test)

# Print details of the Bagging Decision Trees model
print("Bagging Decision Trees:")
print("Best Parameters:", grid_bag_dt.best_params_)
print("Best Score:", grid_bag_dt.best_score_)
print_metrics(y_test, y_pred_bag_dt)
print("\n")

Bagging Decision Trees:
Best Parameters: {'max_features': 0.5, 'max_samples': 1.0, 'n_estimators': 800}
Best Score: 0.49120879120879124
Accuracy: 0.5882352941

Micro-average:
Precision: 0.5882352941
Recall: 0.5882352941
F1 Score: 0.5882352941

Macro-average:
Precision: 0.5055555556
Recall: 0.5972222222
F1 Score: 0.5277777778

Weighted-average:
Precision: 0.5058823529
Recall: 0.5882352941
F1 Score: 0.5196078431




##AdaBoost with Decision Trees

In [ ]:
ada_dt = AdaBoostClassifier(base_estimator=DecisionTreeClassifier())
ada_dt_params = {
    'n_estimators': [50, 100, 200, 400, 800],
    'learning_rate': [0.001, 0.01, 0.1, 0.2, 0.5],
}
grid_ada_dt = GridSearchCV(ada_dt, ada_dt_params, cv=5)
grid_ada_dt.fit(X_train, y_train)
y_pred_ada_dt = grid_ada_dt.predict(X_test)

# Print details of the AdaBoost with Decision Trees model
print("AdaBoost with Decision Trees:")
print("Best Parameters:", grid_ada_dt.best_params_)
print("Best Score:", grid_ada_dt.best_score_)
print_metrics(y_test, y_pred_ada_dt)
print("\n")

AdaBoost with Decision Trees:
Best Parameters: {'learning_rate': 0.001, 'n_estimators': 50}
Best Score: 0.4637362637362637
Accuracy: 0.5882352941

Micro-average:
Precision: 0.5882352941
Recall: 0.5882352941
F1 Score: 0.5882352941

Macro-average:
Precision: 0.4722222222
Recall: 0.5972222222
F1 Score: 0.5079365079

Weighted-average:
Precision: 0.5000000000
Recall: 0.5882352941
F1 Score: 0.5182072829




##XGBoost

In [ ]:
import xgboost as xgb
y_train_reduced = y_train - 1
y_test_reduced = y_test - 1

# Rest of your code remains the same
xgb_model = xgb.XGBClassifier()
xgb_params = {
    'max_depth': [3, 5, 7, 9],
    'learning_rate': [0.001, 0.01, 0.1, 0.2, 0.5],
    'n_estimators': [50, 100, 200, 400, 800],
    'gamma': [0, 0.1, 0.2, 0.3],
    'subsample': [0.8, 0.9, 1.0],
    'colsample_bytree': [0.8, 0.9, 1.0],
    'reg_alpha': [0, 0.01, 0.1, 1, 10],
    'reg_lambda': [0, 0.01, 0.1, 1, 10]
}
grid_xgb = GridSearchCV(xgb_model, xgb_params, cv=5)
grid_xgb.fit(X_train, y_train_reduced)
y_pred_xgb = grid_xgb.predict(X_test)

# Print details of the XGBoost model
print("XGBoost:")
print("Best Parameters:", grid_xgb.best_params_)
print("Best Score:", grid_xgb.best_score_)
print_metrics(y_test_reduced, y_pred_xgb)
print("\n")


##Catboost

In [ ]:
!pip install catboost

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.6/98.6 MB 4.5 MB/s eta 0:00:00


In [ ]:
from catboost import CatBoostClassifier
cboost = CatBoostClassifier()

parameters = [{'n_estimators': [1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000]}]
grid_search = GridSearchCV(estimator = cboost,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

Learning rate set to 0.027245
0:	learn: 1.7822836	total: 47ms	remaining: 2m 21s
1:	learn: 1.7766215	total: 48.2ms	remaining: 1m 12s
2:	learn: 1.7704793	total: 49.2ms	remaining: 49.2s
3:	learn: 1.7605066	total: 50.3ms	remaining: 37.7s
4:	learn: 1.7499156	total: 51.3ms	remaining: 30.8s
5:	learn: 1.7435182	total: 52.4ms	remaining: 26.1s
6:	learn: 1.7343815	total: 53.5ms	remaining: 22.9s
7:	learn: 1.7256469	total: 54.7ms	remaining: 20.4s
8:	learn: 1.7161294	total: 55.7ms	remaining: 18.5s
9:	learn: 1.7067897	total: 56.8ms	remaining: 17s
10:	learn: 1.6968486	total: 57.9ms	remaining: 15.7s
11:	learn: 1.6888452	total: 58.9ms	remaining: 14.7s
12:	learn: 1.6826418	total: 60ms	remaining: 13.8s
13:	learn: 1.6740484	total: 61ms	remaining: 13s
14:	learn: 1.6657648	total: 62ms	remaining: 12.3s
15:	learn: 1.6582153	total: 63.1ms	remaining: 11.8s
16:	learn: 1.6494299	total: 64.3ms	remaining: 11.3s
17:	learn: 1.6413451	total: 65.4ms	remaining: 10.8s
18:	learn: 1.6320474	total: 66.5ms	remaining: 10.4s
19

##ADABoost

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import AdaBoostClassifier
ada = AdaBoostClassifier()

parameters = [{'estimator': [RandomForestClassifier(), GradientBoostingClassifier()], 'n_estimators': [1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000]}]
grid_search = GridSearchCV(estimator = ada,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

Best Accuracy: 59.52 %
Best Parameters: {'estimator': RandomForestClassifier(), 'n_estimators': 9000}


In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
ada = AdaBoostClassifier()

parameters = [{'estimator': [AdaBoostClassifier(estimator=RandomForestClassifier(n_estimators=5000), n_estimators=10000, learning_rate=0.01)], 'n_estimators': [10, 50, 100, 500, 1000, 2000, 5000], 'learning_rate' : [0.1, 0.01, 0.001]}]
grid_search = GridSearchCV(estimator = ada,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

Best Accuracy: 58.10 %
Best Parameters: {'estimator': AdaBoostClassifier(estimator=RandomForestClassifier(n_estimators=5000),
                   learning_rate=0.01, n_estimators=10000), 'learning_rate': 0.1, 'n_estimators': 50}


In [ ]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score


ada2 = AdaBoostClassifier(estimator=GradientBoostingClassifier(n_estimators=5000), n_estimators=10000, learning_rate=0.01, random_state=0)
accuracies = cross_val_score(estimator = ada2, X = X_train, y = y_train, cv = 6)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 58.08 %
Standard Deviation: 8.99 %


In [ ]:
accuracies

array([0.66666667, 0.54545455, 0.54545455, 0.45454545, 0.54545455,
       0.72727273])

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier

ada_final = AdaBoostClassifier(estimator=GradientBoostingClassifier(n_estimators=5000), n_estimators=4000, learning_rate=0.01, random_state=0)
ada_final.fit(X_train, y_train)
y_pred_ada = ada_final.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_ada)

print(cm)
print("\n")
print(accuracy_score(y_test, y_pred_ada)*100)
print(f'Precision : {precision_score(y_test, y_pred_ada, average="macro")}')
print(f'Recall : {recall_score(y_test, y_pred_ada, average="macro")*100}')
print(f'F1 Score : {f1_score(y_test, y_pred_ada, average="macro")*100}')

[[2 0 0 0 0 0]
 [0 3 0 0 0 0]
 [0 1 0 2 0 0]
 [0 0 0 2 1 0]
 [0 0 0 0 1 1]
 [1 0 0 2 1 0]]


47.05882352941176
Precision : 0.34722222222222215
Recall : 52.77777777777778
F1 Score : 41.69312169312169


##PICKLE

In [19]:
import pickle

with open('RMSSD_model_wBA.pkl', 'wb') as f:
    pickle.dump(grid_bag, f)

In [ ]:
# import pickle

# with open('STAI_model_Final_wBA.pkl', 'rb') as f:
#     model = pickle.load(f)

# y_pred_f = model.predict([[1, 35, 0, 1, 1, 0, 1, 26.7]])
# print(y_pred_f)

In [ ]:
# print(model)