#Preprocessing


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV

In [ ]:
df = pd.read_csv('/content/final_data_SDNN.csv')
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [ ]:
df.columns

Index(['ID', 'Gender', 'Age', 'Alchohol', 'Smoking', 'Non-Veg', 'Exercise',
       'Medication', 'BMI', 'SDNN_best'],
      dtype='object')

In [ ]:
X['Gender'] = X['Gender'].apply(lambda x: 0 if x == 'Male' else 1)
X['Alchohol'] = X['Alchohol'].apply(lambda x: 0 if x == 'No' else 1)
X['Smoking'] = X['Smoking'].apply(lambda x: 0 if x == 'No' else 1)
X['Non-Veg'] = X['Non-Veg'].apply(lambda x: 0 if x == 'No' else 1)
X['Exercise'] = X['Exercise'].apply(lambda x: 0 if x == 'No' else 1)
X['Medication'] = X['Medication'].apply(lambda x: 0 if x == 'No' else 1)
X.head()

ID  Gender  Age  Alchohol  Smoking  Non-Veg  Exercise  Medication   BMI
0  S_1       0   37         0        0        0         0           0  24.1
1  S_2       0   47         0        0        0         1           1  22.8
2  S_3       1   47         0        0        0         0           1  28.0
3  S_4       1   35         0        0        0         0           0  27.4
4  S_5       1   33         0        0        0         0           0  22.6

In [ ]:
X.drop('ID',axis=1,inplace=True)

##OverSampler

In [ ]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(sampling_strategy="not majority")
X_res, y_res = ros.fit_resample(X, y)

In [ ]:
y_res.value_counts()

2    14
3    14
5    14
4    14
1    14
6    14
Name: SDNN_best, dtype: int64

In [ ]:
X = X_res.values
y = y_res.values

##Split

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
X_test

array([[ 1. , 39. ,  0. ,  0. ,  1. ,  0. ,  0. , 27.5],
       [ 1. , 37. ,  0. ,  0. ,  1. ,  0. ,  0. , 31.4],
       [ 0. , 28. ,  0. ,  0. ,  1. ,  0. ,  0. , 24.1],
       [ 0. , 28. ,  0. ,  0. ,  0. ,  1. ,  0. , 27.9],
       [ 0. , 30. ,  0. ,  0. ,  1. ,  1. ,  0. , 26.8],
       [ 0. , 30. ,  0. ,  0. ,  1. ,  0. ,  0. , 29. ],
       [ 1. , 47. ,  0. ,  0. ,  0. ,  0. ,  1. , 28. ],
       [ 0. , 34. ,  0. ,  0. ,  1. ,  1. ,  0. , 18.9],
       [ 0. , 41. ,  0. ,  0. ,  0. ,  1. ,  0. , 20.9],
       [ 1. , 35. ,  0. ,  0. ,  1. ,  0. ,  1. , 25. ],
       [ 0. , 37. ,  0. ,  0. ,  1. ,  1. ,  0. , 22.3],
       [ 1. , 34. ,  0. ,  0. ,  0. ,  0. ,  0. , 22.1],
       [ 0. , 47. ,  0. ,  0. ,  0. ,  1. ,  1. , 22.8],
       [ 1. , 43. ,  0. ,  0. ,  0. ,  1. ,  0. , 26.5],
       [ 0. , 28. ,  0. ,  0. ,  1. ,  0. ,  0. , 24.3],
       [ 0. , 34. ,  1. ,  0. ,  1. ,  1. ,  0. , 23.2],
       [ 0. , 28. ,  0. ,  0. ,  1. ,  0. ,  0. , 18.9]])

In [ ]:
X_train.shape

(67, 8)

##Feature-Scaling


In [ ]:
X_scaled_train = X_train
X_scaled_test = X_test

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

cols = [1,7]
scaler = StandardScaler()

scaler.fit(X_scaled_train[:, cols])

X_scaled_train[:, cols] = scaler.transform(X_scaled_train[:, cols])
X_scaled_test[:, cols] = scaler.transform(X_scaled_test[:, cols])

In [ ]:
X_train_normal = X_train
X_test_normal = X_test

from sklearn.preprocessing import Normalizer
nl_1 = Normalizer()

cols = [1,7]

norm = Normalizer()

norm.fit(X_train_normal[:, cols])

X_train_normal[:, cols] = norm.transform(X_train_normal[:, cols])
X_test_normal[:, cols] = norm.transform(X_test_normal[:, cols])

# Models

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostClassifier

##Logistic Regression

In [ ]:
# from sklearn.linear_model import LogisticRegression
# from sklearn.ensemble import AdaBoostClassifier
# classifier = LogisticRegression()
# classifier_boost = AdaBoostClassifier(n_estimators = 10,
#                                       estimator = classifier,
#                                       learning_rate = 1)
# classifier_boost.fit(X_train, y_train)

# y_pred = classifier_boost.predict(X_test)
# cm_2 = confusion_matrix(y_test, y_pred)
# print(cm_2)
# print("\nAccuracy: {:.2f} %".format(accuracy_score(y_test, y_pred)*100))

[[2 0 0 0 0 0]
 [3 0 0 0 0 0]
 [0 1 3 0 0 0]
 [2 0 0 0 0 1]
 [1 0 0 0 0 0]
 [0 0 2 0 1 1]]

Accuracy: 35.29 %


##GradientBossting

In [ ]:
# from sklearn.ensemble import GradientBoostingClassifier
# gboost = GradientBoostingClassifier(n_estimators=11)
# gboost.fit(X_train, y_train)
# y_pred = gboost.predict(X_test)
# cm = confusion_matrix(y_test, y_pred)
# print(f'For 11 trees \n{cm}')
# print(f'Accuracy : {accuracy_score(y_test, y_pred)*100} %\n\n')

For 11 trees 
[[1 0 0 0 1 0]
 [1 2 0 0 0 0]
 [0 1 3 0 0 0]
 [0 0 0 2 1 0]
 [0 0 1 0 0 0]
 [1 0 2 0 1 0]]
Accuracy : 47.05882352941176 %




##DecisionTree

In [ ]:
# from sklearn.tree import DecisionTreeClassifier
# dc = DecisionTreeClassifier()
# dc.fit(X_train, y_train)

# y_pred = dc.predict(X_test)
# cm_2 = confusion_matrix(y_test, y_pred)
# cm_2
# print(f'Accuracy : {accuracy_score(y_test, y_pred)*100} %\n\n')

Accuracy : 52.94117647058824 %




##Random Forest


In [ ]:
# from sklearn.ensemble import RandomForestClassifier
# rforest = RandomForestClassifier()

# parameters = [{'criterion': ['gini', 'entropy', 'log_loss'],
#                'n_estimators': [100 ,200 ,300,400,500,600,700,800,900,1000,1100,1200,1300,1400,1500,3000,4000]}]
# grid_search = GridSearchCV(estimator = rforest,
#                            param_grid = parameters,
#                            scoring = 'accuracy',
#                            cv = 10,
#                            n_jobs = -1)
# grid_search.fit(X_train, y_train)
# best_accuracy = grid_search.best_score_
# best_parameters = grid_search.best_params_
# print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
# print("Best Parameters:", best_parameters)

Best Accuracy: 54.76 %
Best Parameters: {'criterion': 'gini', 'n_estimators': 100}


##SVC

In [ ]:
# from sklearn.svm import SVC
# svc = SVC()

# parameters = [{'C': [0.1,0.5,1,1.5,2,5, 10, 100, 1000],
#               'gamma': [100,10, 1, 0.1, 0.01, 0.001, 0.0001],
#               'kernel': ['rbf','linear', 'poly','sigmoid'],
#               'shrinking': [True, False],
#               'degree': [1,2,3],
#               'probability': [True, False],
#               'verbose': [True, False]}]
# grid_search = GridSearchCV(estimator = svc,
#                            param_grid = parameters,
#                            scoring = 'accuracy',
#                            cv = 10,
#                            n_jobs = -1)
# grid_search.fit(X_train, y_train)
# best_accuracy = grid_search.best_score_
# best_parameters = grid_search.best_params_
# print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
# print("Best Parameters:", best_parameters)

[LibSVM]Best Accuracy: 63.81 %
Best Parameters: {'C': 1, 'degree': 1, 'gamma': 100, 'kernel': 'rbf', 'probability': True, 'shrinking': True, 'verbose': True}


In [ ]:
from sklearn.svm import SVC
svc = SVC()

parameters = [{'C': [1],
              'gamma': [10,100,200,300],
              'kernel': ['rbf'],
              'shrinking': [True, False],
              'degree': [1,2,3],
              'probability': [True, False],
              'verbose': [True, False]}]
grid_search = GridSearchCV(estimator = svc,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

[LibSVM]Best Accuracy: 65.71 %
Best Parameters: {'C': 1, 'degree': 1, 'gamma': 10, 'kernel': 'rbf', 'probability': True, 'shrinking': True, 'verbose': True}


###Predictions

In [ ]:
y_ex = [[1,47,0,0,0,0,1,23]]
y_ex_pred = grid_search.predict(y_ex)
dict = {1:"ANYB",2:"OM Chanting",3:"MM",4:"Shavasan",5:"Quiet Sitting",6:"Spine Rest"}
for i in y_ex_pred:
  print(dict[i])

Spine Rest


##Catboost

In [ ]:
!pip install catboost

from sklearn.model_selection import cross_val_score
from catboost import CatBoostClassifier
cboost = CatBoostClassifier()
accuracies = cross_val_score(estimator = cboost, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

parameters = [{'n_estimators': [1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000]}]
grid_search = GridSearchCV(estimator = cboost,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1,
                           verbose = 0)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

Streaming output truncated to the last 5000 lines.
8:	learn: 1.5891336	total: 32.4ms	remaining: 3.57s
9:	learn: 1.5706318	total: 33.5ms	remaining: 3.32s
10:	learn: 1.5489638	total: 34.6ms	remaining: 3.11s
11:	learn: 1.5316245	total: 35.8ms	remaining: 2.94s
12:	learn: 1.5141252	total: 37ms	remaining: 2.81s
13:	learn: 1.4955007	total: 38.5ms	remaining: 2.71s
14:	learn: 1.4758067	total: 40.7ms	remaining: 2.67s
15:	learn: 1.4566235	total: 47ms	remaining: 2.89s
16:	learn: 1.4379487	total: 48.4ms	remaining: 2.8s
17:	learn: 1.4192092	total: 49.6ms	remaining: 2.7s
18:	learn: 1.4014496	total: 51.1ms	remaining: 2.64s
19:	learn: 1.3865354	total: 52.5ms	remaining: 2.57s
20:	learn: 1.3697006	total: 58.1ms	remaining: 2.71s
21:	learn: 1.3566826	total: 61.6ms	remaining: 2.74s
22:	learn: 1.3422363	total: 62.8ms	remaining: 2.67s
23:	learn: 1.3241336	total: 63.9ms	remaining: 2.6s
24:	learn: 1.3074093	total: 68.8ms	remaining: 2.68s
25:	learn: 1.2954309	total: 69.8ms	remaining: 2.62s
26:	learn: 1.2842975	t

##ADABoost

In [ ]:
# from sklearn.ensemble import AdaBoostClassifier
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.ensemble import GradientBoostingClassifier
# ada = AdaBoostClassifier()

# parameters = [{'estimator': [RandomForestClassifier(), GradientBoostingClassifier()], 'n_estimators': [1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000]}]
# grid_search = GridSearchCV(estimator = ada,
#                            param_grid = parameters,
#                            scoring = 'accuracy',
#                            cv = 10,
#                            n_jobs = -1)
# grid_search.fit(X_train, y_train)
# best_accuracy = grid_search.best_score_
# best_parameters = grid_search.best_params_
# print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
# print("Best Parameters:", best_parameters)

Best Accuracy: 54.29 %
Best Parameters: {'estimator': GradientBoostingClassifier(), 'n_estimators': 8000}


##new

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

max_cm=0
best_ac=0
for i in range(100):
  n_esti = [3000,4000,5000,6000]
  ada_final = AdaBoostClassifier(estimator=GradientBoostingClassifier(n_estimators=5000), n_estimators=4000, learning_rate=0.01, random_state=0)
  ada_final.fit(X_train, y_train)
  y_pred = ada_final.predict(X_test)

  cm = confusion_matrix(y_test, y_pred)
  curr_ac = accuracy_score(y_test, y_pred)*100

  if(curr_ac>best_ac):
    max_cm = cm
    best_ac = curr_ac
print(max_cm)
print("\n")
print("Best Accuracy: {:.2f} %".format(best_ac))

[[1 0 0 0 1 0]
 [0 3 0 0 0 0]
 [0 2 0 2 0 0]
 [0 0 0 2 1 0]
 [0 0 0 0 1 0]
 [0 0 0 1 1 2]]


Best Accuracy: 52.94 %


##Ensemble

In [ ]:
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import RandomForestClassifier


best_gboost = GradientBoostingClassifier(n_estimators=1000, learning_rate=0.3)
best_rforest = RandomForestClassifier(n_estimators=780)


estimators = [('gboost', best_gboost), ('rf', best_rforest)]
ensemble_1 = VotingClassifier(estimators, voting='hard')
ensemble_2 = VotingClassifier(estimators, voting='hard')

ensemble_1.fit(X_train, y_train)
ensemble_2.fit(X_scaled_train, y_train)

print(f'Simple Train : {ensemble_1.score(X_test, y_test)}')
print(f'Scaled Train : {ensemble_2.score(X_scaled_test, y_test)}')

Simple Train : 0.4117647058823529
Scaled Train : 0.4117647058823529


##XGBoost

In [ ]:
import xgboost as xgb

from sklearn.model_selection import GridSearchCV
xgb_model = xgb.XGBClassifier()
y_train
parameters = [{'n_estimators': [10, 50, 100, 500, 1000, 1500, 2000],
               'learning_rate' : [0.1, 0.01, 0.001, 0.0001],
               'tree_method' : ['approx', 'hist']}]
grid_search = GridSearchCV(estimator = xgb_model,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search.fit(X_scaled_train, (y_train - 1))
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)


Best Accuracy: 58.57 %
Best Parameters: {'learning_rate': 0.1, 'n_estimators': 50, 'tree_method': 'approx'}


In [ ]:
from sklearn.model_selection import cross_val_score
xg_model2 = xgb.XGBClassifier(n_estimators=10, learning_rate=0.1, tree_methods='approx')
accuracies = cross_val_score(estimator = xg_model2, X = X_scaled_train, y = (y_train-1), cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

[01:43:13] WARNING: ../src/learner.cc:767: 
Parameters: { "tree_methods" } are not used.

[01:43:13] WARNING: ../src/learner.cc:767: 
Parameters: { "tree_methods" } are not used.

[01:43:13] WARNING: ../src/learner.cc:767: 
Parameters: { "tree_methods" } are not used.

[01:43:13] WARNING: ../src/learner.cc:767: 
Parameters: { "tree_methods" } are not used.

[01:43:13] WARNING: ../src/learner.cc:767: 
Parameters: { "tree_methods" } are not used.

[01:43:13] WARNING: ../src/learner.cc:767: 
Parameters: { "tree_methods" } are not used.

[01:43:13] WARNING: ../src/learner.cc:767: 
Parameters: { "tree_methods" } are not used.

[01:43:13] WARNING: ../src/learner.cc:767: 
Parameters: { "tree_methods" } are not used.

[01:43:13] WARNING: ../src/learner.cc:767: 
Parameters: { "tree_methods" } are not used.

[01:43:13] WARNING: ../src/learner.cc:767: 
Parameters: { "tree_methods" } are not used.

Accuracy: 48.33 %
Standard Deviation: 11.37 %
